<div class="container">
                <div class="span1">&nbsp;</div>
                <!--Sidebar content-->
                <div class="span2"> 
                        <div class="row">
                                <div class="widget ">
                                        <div class="widget-header"> <i class="icon-user"></i>
                                                <h3>MENU</h3>
                                        </div>
                                </div>
                                <div class="widget-content">
                                        <ul class="nav nav-list">
                                   <li class="active"><a href="/admin/listings/add"><i class="icon-home"></i>General Detail</a></li>
                                     <li ><a href="/admin/listings/photo"><i class="icon-book"></i>Photo</a></li>
                                     <li><a href="/admin/listings/aminities"><i class="icon-list"></i>Aminities</a></li>
                                        </ul>
                                </div>
                        </div>
                </div>
                <!-- end Sidebar content-->
                 <!--general information content-->
                <div class="span8" style="margin-left:0px;> 
                        <div class="widget ">
                                <div class="widget-header"><i class="icon-user"></i>
                                         <h3>General information</h3>
                                </div>
                                <div class="widget-content">
                            <?php
							?>    
                                
                                
             <form id="basic" class="form-horizontal"  method="POST" action="/admin/listings/add" >
                <fieldset>
                    <?php echo $this->form->id; ?>
        
                    <div class="control-group <?php echo (array_key_exists('listing_type_id', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->listing_type_id; ?>
                        <?php if (array_key_exists('listing_type_id', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['listing_type_id']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('status', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->status; ?>
                        <?php if (array_key_exists('status', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['status']; ?></span>
                        <?php } ?>
                    </div>
        
                    <div class="control-group <?php echo (array_key_exists('house_style', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->house_style; ?>
                        <?php if (array_key_exists('house_style', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['house_style']; ?></span>
                        <?php } ?>
                    </div>
                    <!-- /control-group -->
                    <div class="control-group <?php echo (array_key_exists('list_price', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->list_price; ?>
                        <?php if (array_key_exists('list_price', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['list_price']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('listing_date', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->listing_date; ?>
                        <?php if (array_key_exists('listing_date', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['listing_date']; ?></span>
                        <?php } ?>
                    </div>
                   <div class="control-group <?php echo (array_key_exists('city_id', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->city_id; ?>
                        <?php if (array_key_exists('city_id', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['city_id']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('area_id', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->area_id; ?>
                        <?php if (array_key_exists('area_id', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['area_id']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('zip_code', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->zip_code; ?>
                        <?php if (array_key_exists('zip_code', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['zip_code']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('disp_address', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->disp_address; ?>
                        <?php if (array_key_exists('disp_address', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['disp_address']; ?></span>
                        <?php } ?>
                    </div>
		
                         <div class="control-group <?php echo (array_key_exists('description', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->description; ?>
                        <?php if (array_key_exists('description', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['description']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('basement', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->basement; ?>
                        <?php if (array_key_exists('basement', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['basement']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('garage', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->garage; ?>
                        <?php if (array_key_exists('garage', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['garage']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('year_built', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->year_built; ?>
                        <?php if (array_key_exists('year_built', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['year_built']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('lot_size', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->lot_size; ?>
                        <?php if (array_key_exists('lot_size', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['lot_size']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('lot_size_type', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->lot_size_type; ?>
                        <?php if (array_key_exists('lot_size_type', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['lot_size_type']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('sqft_area', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->sqft_area; ?>
                        <?php if (array_key_exists('sqft_area', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['sqft_area']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('bed_rooms', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->bed_rooms; ?>
                        <?php if (array_key_exists('bed_rooms', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['bed_rooms']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('disp_address', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->disp_address; ?>
                        <?php if (array_key_exists('disp_address', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['disp_address']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('bath_rooms', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->bath_rooms; ?>
                        <?php if (array_key_exists('bath_rooms', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['bath_rooms']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('tubs', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->tubs; ?>
                        <?php if (array_key_exists('tubs', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['tubs']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('stalls', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->stalls; ?>
                        <?php if (array_key_exists('stalls', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['stalls']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('roof_type', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->roof_type; ?>
                        <?php if (array_key_exists('roof_type', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['roof_type']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('exterior', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->exterior; ?>
                        <?php if (array_key_exists('exterior', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['exterior']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('interior', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->interior; ?>
                        <?php if (array_key_exists('interior', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['interior']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="control-group <?php echo (array_key_exists('stories', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->stories; ?>
                        <?php if (array_key_exists('stories', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['stories']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('kitchen', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->kitchen; ?>
                        <?php if (array_key_exists('kitchen', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['kitchen']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('room_other', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->room_other; ?>
                        <?php if (array_key_exists('room_other', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['room_other']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('construction', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->construction; ?>
                        <?php if (array_key_exists('construction', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['construction']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('floor', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->floor; ?>
                        <?php if (array_key_exists('floor', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['floor']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('total_floor', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->total_floor; ?>
                        <?php if (array_key_exists('total_floor', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['total_floor']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('facing', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->facing; ?>
                        <?php if (array_key_exists('facing', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['facing']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('heat_system', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->heat_system; ?>
                        <?php if (array_key_exists('heat_system', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['heat_system']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('furnished', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->furnished; ?>
                        <?php if (array_key_exists('furnished', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['furnished']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('ownership_type', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->ownership_type; ?>
                        <?php if (array_key_exists('ownership_type', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['ownership_type']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('latitude', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->latitude; ?>
                        <?php if (array_key_exists('latitude', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['latitude']; ?></span>
                        <?php } ?>
                    </div>
                    <div class="control-group <?php echo (array_key_exists('longitude', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->longitude; ?>
                        <?php if (array_key_exists('longitude', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['longitude']; ?></span>
                        <?php } ?>
                    </div>

                    <div class="form-actions">
                        <input type="submit" class="btn" value="Submit"/>
                        <a href="/admin/reports" class="btn">cancel</a>
        
                    </div>
                    
                </fieldset>
                                        </form>
                                </div>
                        </div>
                </div>
        </div>
</div>
</div>
