<div class="container">
                <div class="span1">&nbsp;</div>
                <!--Sidebar content-->
                <div class="span2"> 
                        <div class="row">
                                <div class="widget ">
                                        <div class="widget-header"> <i class="icon-user"></i>
                                                <h3>MENU</h3>
                                        </div>
                                </div>
                                <div class="widget-content">
                                        <ul class="nav nav-list">
                                     <li ><a href="/admin/listings/add"><i class="icon-home"></i>General Detail</a></li>
                                     <li ><a href="/admin/listings/photo"><i class="icon-book"></i>Photo</a></li>
                                     <li class="active"><a href="/admin/listings/aminities"><i class="icon-list"></i>Aminities</a></li>
                                        </ul>
                                </div>
                        </div>
                </div>
                <!-- end Sidebar content-->
                 <!--general information content-->
                <div class="span8" style="margin-left:0px;> 
                        <div class="widget ">
                                <div class="widget-header"><i class="icon-user"></i>
                                         <h3>General information</h3>
                                </div>
                                <div class="widget-content">
                                
             <form id="basic" class="form-horizontal"  method="POST" action="/admin/listings/aminities" >
                <fieldset>
                </br></br>
                    <?php echo $this->form->id; ?>
                    
                    <div class="control-group <?php echo (array_key_exists('name', $this->errors) ? 'error' : '') ?>">
                        <?php echo $this->form->name; ?>
                        <?php if (array_key_exists('name', $this->errors)) { ?>
                        <span class="help-inline controls cont"><?php echo $this->errors['name']; ?></span>
                        <?php }?>
                    </div>

                                                    <!-- /control-group --> 
                                                        <br />
                                                        <br />
                                                        <br />
                    <div class="form-actions">
                        <input type="submit" class="btn" value="Submit"/>
                        <a href="/admin/reports" class="btn">cancel</a>
        
                    </div>
                                                        <!-- /form-actions -->
                                                </fieldset>
                                        </form>
                                </div>
                        </div>
                </div>
        </div>
</div>
</div>
