<div class="container">
                <div class="span1">&nbsp;</div>
                <!--Sidebar content-->
                <div class="span2"> 
                        <div class="row">
                                <div class="widget ">
                                        <div class="widget-header"> <i class="icon-user"></i>
                                                <h3>MENU</h3>
                                        </div>
                                </div>
                                <div class="widget-content">
                                        <ul class="nav nav-list">
                                     <li ><a href="/admin/listings/add"><i class="icon-home"></i>General Detail</a></li>
                                     <li class="active"><a href="/admin/listings/photo"><i class="icon-book"></i>Photo</a></li>
                                     <li ><a href="/admin/listings/aminities"><i class="icon-list"></i>Aminities</a></li>
                                        </ul>
                                </div>
                        </div>
                </div>
                <!-- end Sidebar content-->
                 <!--general information content-->
                <div class="span8" style="margin-left:0px;> 
                        <div class="widget ">
                                <div class="widget-header"><i class="icon-user"></i>
                                         <h3>Photos</h3>                  
                                     <span style="margin-left:450px;"> <i class="icon-plus"></i> &nbsp;&nbsp;<h3>upload photo</h3></span> <input id="upload" multiple="multiple" type="file" name="uploadfile" style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 118px; margin: 0px; padding: 0px; cursor: pointer; opacity: 0;">

                                </div>
                                <div class="widget-content">
                                
             <form id="basic" class="form-horizontal"  method="POST" action="/admin/listings/aminities" >
                <fieldset>
                </br></br>
                    <?php echo $this->form->id; ?>
                    <span id="status" ></span>  
<!--List Files-->  
<ul id="files" ></ul>  

                    
                                                    <!-- /control-group --> 
                                                        <br />
                                                        <br />
                                                        <br />
                    <div class="form-actions">
                        <input type="submit" class="btn" value="Submit"/>
                        <a href="/admin/reports" class="btn">cancel</a>
        
                    </div>
                                                        <!-- /form-actions -->
                                                </fieldset>
                                        </form>
                                </div>
                        </div>
                </div>
        </div>
</div>
</div>
<script type="text/javascript" src="/js/ajaxupload.3.5.js" ></script>

<script>


$(function(){  
    var btnUpload=$('#upload');  
    var status=$('#status');  
    new AjaxUpload(btnUpload, {  
        action: '/admin/listings/photo/',  
        //Name of the file input box  
        name: 'uploadfile',  
        onSubmit: function(file, ext){  
            if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){   
                  // check for valid file extension   
                status.text('Only JPG, PNG or GIF files are allowed');  
                return false;  
            } 
			 status.text('uploading... ')
        },  
        onComplete: function(file, response){  
            //On completion clear the status  
            status.text('');  
            //Add uploaded file to list  
            if(response==="success"){ 
 
                $('<li></li>').appendTo('#files').html('<img src="/img/media/'+file+'" alt="" /><br />'+file).addClass('success');  
            } else{  
                $('<li></li>').appendTo('#files').html('<img src="/img/media/'+file+'" alt="" width="80px" height="80px" />'+file).addClass('error');  
            }  
        }  
    });  
}); 

 
</script>


