        <link rel="stylesheet" type="text/css" href="/slide/css/style.css" />
		<link href='http://fonts.googleapis.com/css?family=Advent+Pro:100,500' rel='stylesheet' type='text/css'>
    		<noscript>
			<link rel="stylesheet" type="text/css" href="/slide/css/nojs.css" />
		</noscript>
<div class="slide11" style="height:500px;">
<div class="container">
               
 <!-- nivo slider -->
                
        	
			<ul id="sg-panel-container">
				
					<img title="Grexit" src="/img/image1.jpg" />
					<img title="Grexit" src="/img/image1.jpg" />
					<img title="Grexit" src="/img/image1.jpg" />
					<img title="Grexit" src="/img/image1.jpg" />
					<img title="Grexit" src="/img/image1.jpg" />
			
			</ul>
			
			
		</div>
<!-- end nivo slider -->                
                
<!-- start: Slider 
<div class="carousel slide nish2" id="myCarousel">
  <div class="carousel-inner">
    <div class="item"> <img alt="" src="/img/image1.jpg" style="height:423px"> </div>
    <div class="item"> <img alt="" src="/img/image2.jpg" style="height:423px"> </div>
    <div class="item active"> <img alt="" src="/img/image3.jpg" style="height:423px"> </div>
  </div>
  <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a> <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a> </div>
<!-- end: Slider --> 
</div></div></div>

<div id="pane-links" class="container-links">
            <div class="container">
                <div class="row">
                 <ul class="thumbnails" >
                            <div >
                             <li class="span4 show " >
                        <div class="thumbnail" style="margin-left:0px;height:150px;">
                                <h4 style="color:#FFF"><b> SERVICES </b></h4>
                                <ul class="aa">
                                 <li ><a  href="#"><i class="icon-circle-arrow-right"></i> Integration Services	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Application Services 	</a></li>
                                 <li><a href="#"><i class="icon-circle-arrow-right"></i>DW & BI Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Consulting Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Professional Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Staff Augmentation Services 	</a></li>
                                 </ul>
                        </div>
                           
                           </li>
                           </div>
                           
                           
                            <div >
                                                       
                                                    <li class="span4 show " style="">
                        <div class="thumbnail" style="height:150px;">

                                <h4 style="color:#FFF"><b>NEWS</b></h4>
                                <ul class="aa">
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its new incorporation of  Canopy One Solutions India Pvt Ltd. March 2012.</a></li>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                    </ul>
                                    
                                     </div>
                                    
                    </li>
                    </div>
              
                        <div>
                           
                            
                                                    <li class="span4 show " style="">
                        <div class="thumbnail" style="height:150px;height:150px;">
                        
                            <h4 style="color:#FFF"><b>EMPLOYEE LOGIN</b></h4>
                            <ul class="aa">    
                              <li>  <a href="#myModal"  data-toggle="modal"><button type="submit" class="btn"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</button></a>

                        </li></br>
                          <li>    <p>Stay updated subscibe to our newsletter.</p></li>
                           <li>     <form class="form-inline">
                                            <input type="text" class="input-small span2" placeholder="Email">
                                            <button type="submit" class="btn"><i class="icon-check"></i> Subscribe</button>
                                    </form>
                            </li>
                            </ul>
                        </div>
                    </li>
                    </div>
                </ul>
                        
                    </div>
        </div>
    </div>

		<script type="text/javascript" src="/slide/js/modernizr.custom.69142.js"></script> 
		<script type="text/javascript" src="/slide/js/jquery.transit.min.js"></script>
		<script type="text/javascript" src="/slide/js/jquery.imagesloaded.js"></script>
		<script type="text/javascript" src="/slide/js/jquery.ba-dotimeout.min.js"></script>
		<script type="text/javascript" src="/slide/js/jquery.gridgallery.js"></script>
		<script type="text/javascript">	
			$(function() {
			
				$( '#sg-panel-container' ).gridgallery();
				
			
			});
			
			window.setInterval(event, 5000);

				function event() {
				 $j("#right_scroll img").click();
				}
			
		</script>
