<link rel='stylesheet' id='camera-css'  href='/slide2/css/camera.css' type='text/css' media='all'> <div class="slide11">

 <!-- nivo slider -->
                
         <div class="camera_wrap camera_azure_skin" id="camera_wrap_2">
            <div data-thumb="/slide2/images/slides/thumbs/bridge.jpg" data-src="/slide2/images/slides/bridge.jpg">
                <div class="camera_caption fadeFromBottom">
                    Camera is a responsive/adaptive slideshow. <em>Try to resize the browser window</em>
                </div>
            </div>
            <div data-thumb="/slide2/images/slides/thumbs/leaf.jpg" data-src="/slide2/images/slides/leaf.jpg">
                <div class="camera_caption fadeFromBottom">
                    It uses a light version of jQuery mobile, <em>navigate the slides by swiping with your fingers</em>
                </div>
            </div>
            <div data-thumb="/slide2/images/slides/thumbs/road.jpg" data-src="/slide2/images/slides/road.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>It's completely free</em> (even if a donation is appreciated)
                </div>
            </div>
            <div data-thumb="/slide2/images/slides/thumbs/sea.jpg" data-src="/slide2/images/slides/sea.jpg">
                <div class="camera_caption fadeFromBottom">
                    Camera slideshow provides many options <em>to customize your project</em> as more as possible
                </div>
            </div>
            <div data-thumb="/slide2/images/slides/thumbs/shelter.jpg" data-src="/slide2/images/slides/shelter.jpg">
                <div class="camera_caption fadeFromBottom">
                    It supports captions, HTML elements and videos and <em>it's validated in HTML5</em> (<a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.pixedelic.com%2Fplugins%2Fcamera%2F&amp;charset=%28detect+automatically%29&amp;doctype=Inline&amp;group=0&amp;user-agent=W3C_Validator%2F1.2" target="_blank">have a look</a>)
                </div>
            </div>
            <div data-thumb="/slide2/images/slides/thumbs/tree.jpg" data-src="/slide2/images/slides/tree.jpg">
                <div class="camera_caption fadeFromBottom">
                    Different color skins and layouts available, <em>fullscreen ready too</em>
                </div>
             </div>
         </div>
               
<!-- end nivo slider -->                
                
<!-- start: Slider 
<div class="carousel slide nish2" id="myCarousel">
  <div class="carousel-inner">
    <div class="item"> <img alt="" src="/img/image1.jpg" style="height:423px"> </div>
    <div class="item"> <img alt="" src="/img/image2.jpg" style="height:423px"> </div>
    <div class="item active"> <img alt="" src="/img/image3.jpg" style="height:423px"> </div>
  </div>
  <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a> <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a> </div>
<!-- end: Slider --> 


<div id="pane-links" class="container-links">
            <div class="container">
                <div class="row">
                 <ul class="thumbnails" >
                            <div >
                             <li class="span4 show " >
                        <div class="thumbnail" style="margin-left:0px;height:150px;">
                                <h4 style="color:#FFF"><b> SERVICES </b></h4>
                                <ul class="aa">
                                 <li ><a  href="#"><i class="icon-circle-arrow-right"></i> Integration Services	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Application Services 	</a></li>
                                 <li><a href="#"><i class="icon-circle-arrow-right"></i>DW & BI Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Consulting Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Professional Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Staff Augmentation Services 	</a></li>
                                 </ul>
                        </div>
                           
                           </li>
                           </div>
                           
                           
                            <div >
                                                       
                                                    <li class="span4 show " style="">
                        <div class="thumbnail" style="height:150px;">

                                <h4 style="color:#FFF"><b>NEWS</b></h4>
                                <ul class="aa">
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its new incorporation of  Canopy One Solutions India Pvt Ltd. March 2012.</a></li>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                    </ul>
                                    
                                     </div>
                                    
                    </li>
                    </div>
              
                        <div>
                           
                            
                                                    <li class="span4 show " style="">
                        <div class="thumbnail" style="height:150px;height:150px;">
                        
                            <h4 style="color:#FFF"><b>EMPLOYEE LOGIN</b></h4>
                            <ul class="aa">    
                              <li>  <a href="#myModal"  data-toggle="modal"><button type="submit" class="btn"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</button></a>

                        </li></br>
                          <li>    <p>Stay updated subscibe to our newsletter.</p></li>
                           <li>     <form class="form-inline">
                                            <input type="text" class="input-small span2" placeholder="Email">
                                            <button type="submit" class="btn"><i class="icon-check"></i> Subscribe</button>
                                    </form>
                            </li>
                            </ul>
                        </div>
                    </li>
                    </div>
                </ul>
                        
                    </div>
        </div>
    </div>
    
    <script type='text/javascript' src='/slide2/scripts/jquery.mobile.customized.min.js'></script>
    <script type='text/javascript' src='/slide2/scripts/jquery.easing.1.3.js'></script> 
    <script type='text/javascript' src='/slide2/scripts/camera.min.js'></script> 
    <script>
		jQuery(function(){
			
			jQuery('#camera_wrap_1').camera({
				thumbnails: true
			});

			jQuery('#camera_wrap_2').camera({
				height: '400px',
				loader: 'bar',
				pagination: false,
				thumbnails: true
			});
		});
	</script>

