<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/career/applicant.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> Canopy   One provides lucrative and promising careers to its employees. Job seekers will have an opportunity to work with wide range of technologies to develop highly innovative solutions. Employees would experience a sense of belongingness and team spirit with excellent working environment. Canopy One believes in nurturing best talent to ensure highest level of satisfaction to our clients.
 </p>
 </br></br></br>
 </div>
 
 <div class="span3">&nbsp;</div>
 <div class="span2">
 
 <button class="btn btn-large btn-block btn-primary" type="button" style="width:145px;">Register Here</button> 
 </br></br>Not Register yet
 </div>
 <div class="span2">
 
 <button class="btn btn-large btn-block btn-warning" type="button" style="width:145px;">Job Seeker</button>
 </br></br>If you Are Job Seeker
 </div>
 <div class="span3">
 
 <button class="btn btn-large btn-block btn-danger" type="button" style="width:145px;">Log In</button>
 </br></br>If you Are Already Register
 </div>
</div></div></div>


</br></br></br></br></br></br>

