<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/career/culture.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <i class=" icon-circle-arrow-right  "></i> &nbsp;Canopy One is an Equal Opportunity Employer (EOE) and proactively engages minority firms to provide services to our company and to our clients. </p>
   <p></br>
<i class=" icon-circle-arrow-right  "></i> &nbsp; We understand the importance of diversity and embrace it. In our orientation programs, training, and through our management style and corporate culture, Canopy One teaches &nbsp; &nbsp; &nbsp; &nbsp; diversity awareness and develops  &nbsp;  diversity skills that offer us a competitive advantage. </p></br>
<p>
<i class=" icon-circle-arrow-right  "></i> &nbsp; Canopy One cultivates an environment that fosters harmony, understanding and mutual respect.</p></br>
<p>
<i class=" icon-circle-arrow-right  "></i> &nbsp; Canopy One provides our employees and contingent workers with a complete range of benefits.


 </p>
</div></div></div>


</br></br></br></br></br></br>

