<style>
a {
color: #666 !important;
text-decoration: none;
}
a:hover {
color: #f06921 !important;
text-decoration: underline !important;
}
body {
    
    background: #FFF;
}
.fo {
font-size:15px !important;
color: #f06921 !important;

	}

.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/career/current.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
  
   <form class="fo">
   <i class="icon-forward cc"></i> Currents Openings :
 <select>
  <option>Select Country</option>
  <option>India</option>
  <option>USA</option>
  <option>Canada</option>
</select>

 </form>
</div>
   <div class="span12" style="text-align:justify;margin-top:20px;">

<!-- drop down tab -->
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
        <a class="accordion-toggle selected" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <div class="row">
        <div class="span8 fo" >
            Job Title: SAP Project Manager
            </div>
            <div class="span3 fo">
             Apply By: ( MM/DD/YYYY)</div>
             </div>
        </a>
        

        </div>
        <div id="collapseOne" class="accordion-body collapse in">
        <div class="accordion-inner">
         <table>
         <tr><td class="span2 ">Job Code:</td><td>CSAP01</td></tr>
         <tr><td>&nbsp;</td></tr>
         <tr><td class="span2" valign="top">Job Description:</td><td>The client is in need of an experienced Project Manager who has extensive past experience and success planning and leading delivery of IT application projects. Many of these projects will be SAP applications. Must be able Track progress, propose and maintain reporting to client management team. This is a technical role in the sense that the person will be responsible from managing the technical aspects of the project: timelines, team activities, roles, resource management, deliverable dates etc.</td></tr>
           <tr><td>&nbsp;</td></tr>

         <tr><td class="span2">&nbsp;</td><td> <a href="#myModal" role="button" class="btn" data-toggle="modal">view job summary</a></td></tr>
         
         </table>
         
        </div>
        </div>
    </div>
    <div class="accordion-group">
        <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
            Collapsible Group Item #2
        </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse">
        <div class="accordion-inner">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        </div>
        </div>
    </div>
    <div class="accordion-group">
        <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
            Collapsible Group Item #3
        </a>
        </div>
        <div id="collapseThree" class="accordion-body collapse">
        <div class="accordion-inner">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">SAP Project Manager : CSAP01</h3>
  </div>
  <div class="modal-body">
    <p>
    <table>
    
    <tr><td>
Herdon, VA
Length: 6 Mos C2H
Start: ASAP
Interview: phone/Skype
65-70 all inclusive
 </td></tr>
 <tr><td>

Description:
 </td></tr>
 <tr><td>
The client is in need of an experienced Project Manager who has extensive past experience and success planning and leading delivery of IT application projects. Many of these projects will be SAP applications. Must be able Track progress, propose and maintain reporting to client management team. This is a technical role in the sense that the person will be responsible from managing the technical aspects of the project: timelines, team activities, roles, resource management, deliverable dates etc.
 </td></tr>
 <tr><td>
Required Skills:
</td></tr>
<tr><td>
<ul>
<li> Strong SAP experience as a project manager </li>
<li> Indirect Procurement is essential</li>
<li>Process experience is essential</li>
</ul>
</td></tr>
<tr><td> 
Nice to Have's:
</td></tr>
<tr><td>
<ul>
<li> French as a second language </li>

<li> PMP certification preferred </li>
<li> Experience in Aerospace HUGE PLUS</li>
</ul>
</td></tr>
</table>
    
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>






</div></div></div>


</br></br></br></br></br></br>

