<!-- start: Slider -->
<div class="carousel slide nish2" id="myCarousel">
  <div class="carousel-inner">
    <div class="item"> <img alt="" src="/img/image1.jpg" > </div>
    <div class="item"> <img alt="" src="/img/image2.jpg" > </div>
    <div class="item active"> <img alt="" src="/img/image3.jpg"> </div>
  </div>
  <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a> <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a> </div>
<!-- end: Slider --> 
<div id="pane-links" class="container-links">
            <div class="container">
                <div class="row">
                            <div class="span6">
                                <h3> About Us</h3>
                                <img alt="" src="/img/banner.jpg">
                                <p>Canopy One Solutions is in the business of providing technology solutions partnering with IT companies ranging from Mid-scale to large scale firms. Canopy one has experienced professionals with abundant skills and talent gained over the years working in different industry sector. </p>
                        </div>
                            <div class="span3">
                                <h3>Latest News</h3>
                                <ul >
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its new incorporation of  Canopy One Solutions India Pvt Ltd. March 2012.</a></li></br>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                    </ul>
                        </div>
                            <div class="span3">
                                    <h3>  Canopy One Solutions</h3>
                                <address>
                                    Inc4229,Lafayette Center Dr Suite#1625,<br>
                                    Chantilly, VA-20151 <br>
                                   
                                    Telephone: 703-831-8282</br>
                                    FAX: 703-345-0515</br>
                                    E-mail: Canopyinfo@CanopyOnesolutions.com 
                                 </address>
                                <h3>Newsletter</h3>
                                <p>Stay updated subscibe to our newsletter.</p>
                                <form class="form-inline">
                                            <input type="text" class="input-small span2" placeholder="Email">
                                            <button type="submit" class="btn"><i class="icon-check"></i> Subscribe</button>
                                    </form>
                        </div>
                    </div>
        </div>
    </div>
