<style>

.test1 {
					    margin-top:-30px;height:170px;
                        border-left:#696969 1px solid;
                        border-right:#696969 1px solid;
                        border-top:#696969 1px solid;
  					    border-bottom:#696969 4px solid !important;
                        background:#fff
}

.test1:hover{
 border-bottom: 4px solid #f06921 !important;
-webkit-transition:border-bottom 1s ease;
-moz-transition:border-bottom 1s ease;
-o-transition:border-bottom 1s ease;
transition:border-bottom 1s ease;
 border-left:#f06921 1px solid;
		 -webkit-transition:border-left 1s ease;
		-moz-transition:border-left 1s ease;
		-o-transition:border-left 1s ease;
		transition:border-left 1s ease;

                        border-right:#f06921 1px solid;
						-webkit-transition:border-right 1s ease;
-moz-transition:border-right 1s ease;
-o-transition:border-right 1s ease;
transition:border-right 1s ease;

                        border-top:#f06921 1px solid;
-webkit-transition:border-top 1s ease;
-moz-transition:border-top 1s ease;
-o-transition:border-top 1s ease;
transition:border-top 1s ease;

}
.test1>h4 { 
background: url(/img/page_bg.png);
background-size:100% 30px; 
margin-left:-3px;
margin-right:-3px;
margin-bottom:6px;
}
.go
{
	background: #f06921;
	-webkit-transition:background 1s ease;
-moz-transition:background 1s ease;
-o-transition:background 1s ease;
transition:background 1s ease;
}
#news li{ list-style: url(/img/li.png) !important; margin-left: 21px;
    margin-top: 4px;}
	
</style>


<link rel='stylesheet' id='camera-css'  href='/slide2/css/camera.css' type='text/css' media='all'> 
<div class="row" style="margin-top:8px;">
 <!-- nivo slider -->
<div class="camera_wrap camera_azure_skin" id="camera_wrap_1" style="display: block; margin-bottom: 0px; height: 10% !important;boder-bottom:2px solid #C66;">                
            <div data-thumb="/img/1thumb.jpg" data-src="/img/1.png">
                <div class="camera_caption fadeFromBottom">
                    &nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </div>
            <div data-thumb="/img/2thumb.jpg" data-src="/img/2.png">
                <div class="camera_caption fadeFromBottom">
                   &nbsp;&nbsp;&nbsp;&nbsp; 
                </div>
            </div>
            <div data-thumb="/img/3thumb.jpg" data-src="/img/3.png">
                <div class="camera_caption fadeFromBottom">
                   &nbsp;&nbsp;&nbsp;&nbsp; 
                </div>
            </div>
            <div data-thumb="/img/4thumb.jpg" data-src="/img/4.png">
                <div class="camera_caption fadeFromBottom">
                   &nbsp;&nbsp;&nbsp;&nbsp; 
                </div>
            </div>
        
<!-- end nivo slider -->                
                
<!-- start: Slider 
<div class="carousel slide nish2" id="myCarousel">
  <div class="carousel-inner">
    <div class="item"> <img alt="" src="/img/image1.jpg" style="height:423px"> </div>
    <div class="item"> <img alt="" src="/img/image2.jpg" style="height:423px"> </div>
    <div class="item active"> <img alt="" src="/img/image3.jpg" style="height:423px"> </div>
  </div>
  <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a> <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a> </div>
<!-- end: Slider --> 
</div> </div>
<div id="pane-links" class="container-links" style="margin-top:-57px;">
            <div class="container">
                <div class="row">
                 <ul class="thumbnails" >
                            <div >
                             <li class="span4 show " >
                        <div class="thumbnail test1" id="te" >
                                <h4 style="color:#000;border-bottom:#000 1px dotted;" id="test2"><b> &nbsp;&nbsp;&nbsp;&nbsp; SERVICES </b></h4>
                                
                                <ul class="aa">
                                 <li ><a  href="#"><i class="icon-circle-arrow-right"></i> Integration Services	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Application Services 	</a></li>
                                 <li><a href="#"><i class="icon-circle-arrow-right"></i>DW & BI Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Consulting Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Professional Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Staff Augmentation Services 	</a></li>
                                 </ul>
                        </div>
                           
                           </li>
                           </div>
                           
                           
                            <div >
                                                       
                                                    <li class="span4 show " style="">
                        <div class="thumbnail test1" >

                                <h4 style="color:#000;border-bottom:#000 1px dotted;" class="test2"><b> &nbsp;&nbsp;&nbsp;&nbsp;NEWS</b></h4>
                                
                                <ul class="aa" id="news">
                                            <li><a class="aa" href="#"> 	Canopy One started its new incorporation of  Canopy One Solutions India Pvt Ltd. March 2012.</a></li>
                                            <li><a class="aa" href="#"> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                            <li><a class="aa" href="#"> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                    </ul>
                                    
                                     </div>
                                    
                    </li>
                    </div>
              
                        <div>
                           
                            
                                                    <li class="span4 show " style="">
                        <div class="thumbnail test1">
                       
                            <h4 style="color:#000;border-bottom:#000 1px dotted;" class="test2"><b> &nbsp;&nbsp;&nbsp;&nbsp;EMPLOYEE LOGIN</b></h4>
                            <ul class="aa">    
                              <li>  <a href="#myModal"  data-toggle="modal"><button type="submit" class="btn"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</button></a>

                        </li>
                          <li> </br>   <p style="color:#666;">Stay updated subscibe to our newsletter.</p></li>
                           <li>     <form class="form-inline">
                                            <input type="text" class="input-small span2" placeholder="Email">
                                            <button type="submit" class="btn"><i class="icon-check"></i> Subscribe</button>
                                    </form>
                            </li>
                            </ul>
                        </div>
                    </li>
                    </div>
                </ul>
                        
                    </div>
        </div>
    </div>
    
    
    
    
    <script type='text/javascript' src='/slide2/scripts/jquery.mobile.customized.min.js'></script>
    <script type='text/javascript' src='/slide2/scripts/jquery.easing.1.3.js'></script> 
    <script type='text/javascript' src='/slide2/scripts/camera.min.js'></script> 
    <script>
		jQuery(function(){
			
			jQuery('#camera_wrap_1').camera({
				thumbnails: false,
				height: '550px',
				hover: false,
				time : 300,	
		
		transPeriod	: 1200,	
			});

			jQuery('#camera_wrap_2').camera({
				height: '400px',
				loader: 'bar',
				pagination: false,
				thumbnails: true
			});
		});
		
		$("#te").hover( function(){ $("#test2").addClass("go");})
	</script>

