     <link rel="stylesheet" href="/nivo/themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/nivo/themes/light/light.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/nivo/themes/dark/dark.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/nivo/themes/bar/bar.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/nivo/nivo-slider.css" type="text/css" media="screen" />
<div class="slide11">
<div class="container">
                <div class="row">
 <!-- nivo slider -->
                
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img src="/img/1.jpg" data-thumb="images/toystory.jpg" alt="" />
                <a href=""><img src="/img/2.jpg" data-thumb="images/up.jpg" alt=""  /></a>
                <img src="/img/3.jpg" data-thumb="images/walle.jpg" alt="" data-transition="slideInLeft" />
                <img src="/img/4.jpg" data-thumb="images/nemo.jpg" alt=""  />
            </div>
        </div>

    </div>
               
<!-- end nivo slider -->                
                
<!-- start: Slider 
<div class="carousel slide nish2" id="myCarousel">
  <div class="carousel-inner">
    <div class="item"> <img alt="" src="/img/image1.jpg" style="height:423px"> </div>
    <div class="item"> <img alt="" src="/img/image2.jpg" style="height:423px"> </div>
    <div class="item active"> <img alt="" src="/img/image3.jpg" style="height:423px"> </div>
  </div>
  <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a> <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a> </div>
<!-- end: Slider --> 
</div></div></div>

<div id="pane-links" class="container-links">
            <div class="container">
                <div class="row">
                 <ul class="thumbnails" >
                            <div >
                             <li class="span4 show " >
                        <div class="thumbnail" style="margin-left:0px;height:150px;">
                                <h4 style="color:#FFF"><b> SERVICES </b></h4>
                                <ul class="aa">
                                 <li ><a  href="#"><i class="icon-circle-arrow-right"></i> Integration Services	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Application Services 	</a></li>
                                 <li><a href="#"><i class="icon-circle-arrow-right"></i>DW & BI Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Consulting Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Professional Services 	</a></li>
                                 <li><a  href="#"><i class="icon-circle-arrow-right"></i>Staff Augmentation Services 	</a></li>
                                 </ul>
                        </div>
                           
                           </li>
                           </div>
                           
                           
                            <div >
                                                       
                                                    <li class="span4 show " style="">
                        <div class="thumbnail" style="height:150px;">

                                <h4 style="color:#FFF"><b>NEWS</b></h4>
                                <ul class="aa">
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its new incorporation of  Canopy One Solutions India Pvt Ltd. March 2012.</a></li>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                    </ul>
                                    
                                     </div>
                                    
                    </li>
                    </div>
              
                        <div>
                           
                            
                                                    <li class="span4 show " style="">
                        <div class="thumbnail" style="height:150px;height:150px;">
                        
                            <h4 style="color:#FFF"><b>EMPLOYEE LOGIN</b></h4>
                            <ul class="aa">    
                              <li>  <a href="#myModal"  data-toggle="modal"><button type="submit" class="btn"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</button></a>

                        </li></br>
                          <li>    <p>Stay updated subscibe to our newsletter.</p></li>
                           <li>     <form class="form-inline">
                                            <input type="text" class="input-small span2" placeholder="Email">
                                            <button type="submit" class="btn"><i class="icon-check"></i> Subscribe</button>
                                    </form>
                            </li>
                            </ul>
                        </div>
                    </li>
                    </div>
                </ul>
                        
                    </div>
        </div>
    </div>
    
    <script type="text/javascript" src="nivo/jquery.nivo.slider.js"></script>
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>

