<div class="slide11">
<div class="container">
                <div class="row">
<!-- start: Slider -->
<div class="carousel slide nish2" id="myCarousel">
  <div class="carousel-inner">
    <div class="item"> <img alt="" src="/img/image1.jpg" style="height:423px"> </div>
    <div class="item"> <img alt="" src="/img/image2.jpg" style="height:423px"> </div>
    <div class="item active"> <img alt="" src="/img/image3.jpg" style="height:423px"> </div>
  </div>
  <a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a> <a data-slide="next" href="#myCarousel" class="right carousel-control">›</a> </div>
<!-- end: Slider --> 
</div></div></div>
<div id="pane-links" class="container-links">
            <div class="container">
                <div class="row">
                            <div class="span6">
                                <h4 style="color:#FFF"><b> ABOUT </b></h4>
                                <img alt="" src="/img/banner.jpg">
                                <p>Canopy One Solutions is in the business of providing technology solutions partnering <a href=""><font color="#f06921">Read More</font></a> </p>
                        </div>
                            <div class="span3">
                                <h4 style="color:#FFF"><b>NEWS</b></h4>
                                <ul >
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its new incorporation of  Canopy One Solutions India Pvt Ltd. March 2012.</a></li></br>
                                            <li><a class="aa" href="#"><i class="icon-circle-arrow-right"></i> 	Canopy One started its Canada Operations through  Canopy One Solutions Canada Inc. </a></li>
                                    </ul>
                        </div>
                            <div class="span3">
                                <h4 style="color:#FFF"><b>EMPLOYEE LOGIN</b></h4>
                                
                                <a href="#myModal"  data-toggle="modal"><button type="submit" class="btn"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</button></a>

                        </br></br>
                                <p>Stay updated subscibe to our newsletter.</p>
                                <form class="form-inline">
                                            <input type="text" class="input-small span2" placeholder="Email">
                                            <button type="submit" class="btn"><i class="icon-check"></i> Subscribe</button>
                                    </form>
                        </div>
                    </div>
        </div>
    </div>
