<!DOCTYPE html>
<html>
<head>
	<title>blog</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
	<link type="text/css" rel="stylesheet" href="assets/css/global.css" />
	<link type="text/css" rel="stylesheet" href="assets/css/color-button.css" />
	<!-- js Boots_from -->
	<script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/custom.js"></script>
	<!-- end Boots_from -->
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50" data-twttr-rendered="true">

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">
				<span>Choose</span><span class="cl-blue">Logo</span>
			</a>
			<div class="nav-collapse">
				<ul class="nav pull-right">
              		<li><a href="index.html">Home</a></li>
              		<li><a href="blog.html">Blog</a></li>
              		<li><a href="element.html">Element</a></li>
              		<li><a href="detail.html">Detail</a></li>
              		<li><a href="pricing-plans.html">Pricing Plans</a></li>
					<li><a href="grid-layout.html">Grid Layout</a></li>

              		<li class="divider-vertical"></li>

              		<li class="avatar_small"><a href="account.html"></a></li>
            		<li class="dropdown">
            			<a class="dropdown-toggle" href="#" data-toggle="dropdown">
	            			john doe
	            			<b class="caret"></b>
            			</a>
            			<ul class="dropdown-menu">
							<li>
								<a href="profile.html">
									<i class="icon-user"></i>
									Account Setting  </a>
							</li>
							<li>
								<a href="setting.html">
									<i class="icon-lock"></i> Change Password</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="login.html"><i class="icon-off"></i> Logout</a>
							</li>
						</ul>
            		</li>
            	</ul>
			</div>
		</div>
	</div>
</div>
<!-- end navbar -->






<!--   -->


<div class="footer">
	<div class="container">
		<div class="row">
			<div class="span6 logo-vt">
				<a class="brand" href="#">
					<span>Choose</span><span class="cl-blue">Logo</span>
				</a>
				<span class="coppy_right">
					<p>Lorem ipsum dolor sit </p>
					<p>@2012 All Rights Reserved.</p>
				</span>
			</div>
			<div class="span2">
				<ul class="nav nav-list">
					<li class="nav-header">Contact</li>
					<li><a href="#">Support</a></li>
					<li><a href="#">About</a></li>
					<li>84.903.197.895</li>
				</ul>
			</div>
			<div class="span2">
				<ul class="nav nav-list">
					<li class="nav-header">Blog</li>
					<li><a href="#">Regulation</a></li>
					<li><a href="#">Blog</a></li>
				</ul>
			</div>
			<div class="span2">
				<ul class="nav nav-list">
					<li class="nav-header">Follow Us</li>
					<li><a href="#"><i class="twitter"></i>Twitter</a></li>
					<li><a href="#"><i class="facebook"></i>Facebook</a></li>
					<li><a href="#"><i class="dd"></i>Forum</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- end footer -->

</body>
</html>
