<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/solution/energy.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">E</span>nergy sector has shown considerable shift from one source of production to another in the recent times. Today advanced nations have started various options to increase their energy requirements by huge investments.  Energy sector depended on highly volatile price structures of crude, ensuring quality crude across all outlets; handling of large supply chains for better delivery has shown heavy fluctuations on cost in the operations. In order to provide smooth production at refineries to delivery of product at the outlets needs a robust technology back up for this industry.  Oil and gas industries dependence on large data and efficient financial monitoring can become possible only with the able technology resources the sector puts into use for its operations across all levels of the operations.</p>
<p>
<span class="dropcap cc">C</span>anopy One has rich experience in Energy Sector serving Oil & Gas, Power Generation, Transmission & Distribution, renewable Energy areas. Canopy One empowers the industry with its industry specific solutions for increased efficiency through various tools and solutions in the area of Data Warehouse and Business Intelligence solutions.

 </p>
</div></div></div>


</br></br></br></br></br></br>

