<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/solution/currency.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">C</span>Success of an industry mainly depends on the transparency and efficiency of managing financial resources. Proven track record of financial stability of the company evidently shows by its loyal customer base.  For better returns on the investment of time and resources financial operation needs an overall control and monitoring constantly. Canopy One helps in managing the large data, related to its products, services, customer's information, financial institutions and federal regulations.  To perform such complex functions managing the information technology resources is essential. Information technology has become an essential part of finance   industry.</p>
<p>
We live in an event-driven world, where change and regulation necessitate increased innovation – and increased productivity. We deliver solutions to Wealth Management, Banking, Capital Markets, and Insurance clients with particular focus on the following business needs:<span class="cc">
Portfolio Performance, Risk Monitoring, Trade Monitoring and Wealth Management</span>

 </p>
</div></div></div>


</br></br></br></br></br></br>

