<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/solution/medical.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> Role of technology has come in to play to a great extent in the past 2 decades in the health care sector. The complexity in involving multi stake-holders role in providing quality healthcare services has become a crucial factor. With the changes in the compliance norms and regulations, it became a necessity to depend on technology for bringing seamless inter-disciplinary functional coordination in the operations. Canopy One helps to bring out end-to-end solutions with its proven knowledge and experience. </p>
   <p> 
Particularly challenging is disparate patient and physician data, as well as sharing information across the enterprise. It's an enormous task, complicated by non-industry-wide standards, traditionally independent departments within organizations, and expanded growth through mergers.
</p>
<p>
Increased competition, patent expirations, and regulatory challenges are increasingly driving Health care companies to focus on productivity and commercialization across their enterprise.</p>
<p>
<div class="bor"></div> 
Canopy One delivers solutions to Healthcare and Pharmaceutical companies with particular emphasis on the following business needs:
</br> </br>
<i class=" icon-circle-arrow-right  "></i> &nbsp;Client Patient Data &nbsp;&nbsp;
<i class=" icon-circle-arrow-right  "></i> &nbsp;Clinical Trial Portals&nbsp;&nbsp;
<i class=" icon-circle-arrow-right  "></i> &nbsp;Drug Brand Compliance&nbsp;&nbsp;


 </p>
</div></div></div>


</br></br></br></br></br></br>

