<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/solution/logistics.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> Industries are expanding to multiple regions creating footprints in multiple locations.  Coordination of various units to perform different operations simultaneously role of technology has become an imminent factor. Transport industries and logistic providers have become corner stone of success for an industry.  Effective logistic solutions have shown the companies the clear-cut   drop in their spending, quicker modes of delivering product and services in shortest possible time, ensuring better customer satisfaction.  Adoption of information technologies becomes important for the sector. </p>
   <p>

Canopy One's know-how in this sector with sound understanding on different technologies can provide dependable solutions to bring out more efficiency and return on investments. </p>
<p>

The operations in a typical transport/logistics sector has been complex and integrating multi functions and multi stake holders of the sector has been crucial in  order to build a suitable solution.  
</p><p>
Canopy One's constant endeavor in order to build tailor made solutions to transport sector keeping in view the logistics, tracking systems coordinating goods dispatch to vehicle movement, to customer monitoring systems, to delivery management apart from other standard modules such as Accounting, billing, Operations management or Insurance coverage etc. 
</br>
<div class="bor"></div>
 The solutions would be built by Canopy one would also ensure the computerized monitoring of 
</br> </br>
<i class=" icon-circle-arrow-right  "></i> &nbsp; vehicle maintenance &nbsp;&nbsp;
<i class=" icon-circle-arrow-right  "></i> &nbsp; engine maintenance &nbsp;&nbsp;
<i class=" icon-circle-arrow-right  "></i> &nbsp;database management &nbsp;&nbsp;
<i class=" icon-circle-arrow-right  "></i> &nbsp; warehouse management modules &nbsp;&nbsp;

</span>

 </p>
</div></div></div>


</br></br></br></br></br></br>

