<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/solution/retail.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">R</span>etail industry has shown considerable change from the past. The buying behavior of a customer started demanding for quality of products and services and value for their money. Today the choice of customer cannot be taken for granted for long.  The movement of customer bases from one product to other has made companies to compete more aggressively to ensure better reach and   satisfaction for the customers with their products and services. Many companies have started expanding their retail outlets within the customer reach by studying large amount data generated out of market research and studies, constant demographic changes, continuous feedback on customer satisfaction levels to sustain in the market place.  Role of technology in retail sector for better quality of product and services has become an essential and integral part of the operations of the sector. </p>
<p>
<span class="dropcapsmall cc">C</span>anopy One Solutions Inc. has been in the sector working on Retail automation projects, enabling VSPs, (Virtual Service Providers) to facilitate entire operations of retail sector. The solutions and experienced team of solutions providers are proven to the best in the industry. The solutions work through a secure environment, provided convenient integration of other modules of the each project.</p>
<p>
 <span class="cc">Our solutions provide end-to-end interfaces to order & procurement, billing, inventory, HR and revenue modules. </span></p>
<h2>Main functionality of the solutions will be</h2>
<p>
<h3><i class=" icon-circle-arrow-right icon-large cc"></i>Customer Relationship Management</h3>
<h3><i class=" icon-circle-arrow-right icon-large cc"></i>Inventory Management</h3>
<h3><i class=" icon-circle-arrow-right icon-large cc"></i>Finance Management</h3>
<h3><i class=" icon-circle-arrow-right icon-large cc"></i>Human resource Management</h3>
<h3><i class=" icon-circle-arrow-right icon-large cc"></i>Customized label user interface , product catalogs, flexible interfaces to resellers for creating their own market identity</h3>
</p>
</br>
<p class="cc">
The entire retail solutions development ensures an end-to-end business suite for the retail sector to conveniently implement and operate through a web based environment.

 </p>
</div></div></div>


</br></br></br></br></br></br>

