<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/solution/telcom.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">G</span>lobal telecom industry is one of the key industries which have come more aggressively in adopting technologies in the recent times than most of the other industries. Any incidence of disruption of services, malfunction or frauds in providing services to the customers or irregularities of statutory norms may lead to total failure of the telecom sector. In order to ensure smooth seamless operations, fool proof technology base is essential for telecom industry to extend services to its customers. Canopy One with its vast experience in telecom sector has provide multiple innovative solutions over the past and even today fully equipped with talented resources to handle projects as…
We live in an unprecedented change in telecommunications for over a decade such as converged networks, massive data growth, and mobile communications is impacting enterprises, carriers, and equipment providers. Customers, employees, and partners expect productive communication tools. </p>
<p>
We deliver communications solutions to enterprises, service providers, and system integrators with particular focus on the following business needs:  <span class="cc">
Network Engineering and Operations and Security</span>

 </p>
</div></div></div>


</br></br></br></br></br></br>

