<style>
body {
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}
.icon-large {
text-align: center;
padding-right: 4px;
}
<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
   <center>  <img src="/img/services/app.png" style="margin-top:8px;" > </center>
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
    
   
   <span style="font-size:15px"><p>
Over the past few years, application development industry has demonstrated a paradigm shiftin customers' demands for more innovative approach towards software solutions development and newer talent of software development.</p>
<p>
Canopy one has a proven approach built over the years, in defining client's requirements, understanding  specifications and designs, to develop, test and integrate software across multiple platforms. The approach is adopted across all the applications including web technologies, enabling your systems to function in any environment.</p>
<p>
Our approach in application development and integrations is based on complete life-cycle application development starting from defining client's requirements, analysis, design, development, implementation, testing and integrating systems through constant interaction with the client's IT personnel jointly in arriving at the acceptance or concurrence of the application development.
Canopy one focuses on providing integrated business applications with thorough understanding on the client's IT environment and legacy systems providing smooth transition to fully stable, scalable and extendable architecture design and application development, keeping in view of the future needs of the client.</p>
<p>
Canopy One application services also include,
<ul style="margin-left:20px;"> 
<li class="icon-circle-arrow-right ">Application design, development, and implementation</li>
<li class="icon-circle-arrow-right ">Systems integration/consolidation</li>
<li class="icon-circle-arrow-right ">Re-engineering, performance tuning and porting services</li>
<li class="icon-circle-arrow-right ">Implementation of packages</li>
<li class="icon-circle-arrow-right ">Feasibility and requirement analysis for business case</li>
</ul>
</p>
<p>
Canopy one believes in providing applications that becomes a value for the clients business. With the constant demand for newer technologies to meet the clients changing needs, Canopy one provides solutions that can conveniently work on cloud or mobility applications giving an additional value to its clients. Canopy one   provides timely delivered and cost-effective solutions with clear focus on high quality. Our experience in providing quality software solutions, project management capabilities and world class standards can give your business the edge on 
<ul style="margin-left:20px;">
<li class="icon-circle-arrow-right ">Java/J2EE solutions</li>
<li class="icon-circle-arrow-right ">.Net Solutions</li>
<li class="icon-circle-arrow-right ">Web and e-commerce</li>
<li class="icon-circle-arrow-right ">Open Source Technology</li>
</ul>
Our application services can transform your entire portfolio taking full benefit of latest technologies   in making them robust to meetthe business needs in the industry.

</p>
   
   </span> 
   </p></div></br></br></br></br>
</div></div>


</br></br></br></br></br></br></br></br></br></br></br></br>

