<style>
body {
    
    background: #FFF;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}
.icon-large {
text-align: center;
padding-right: 4px;
}
<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
   <center>  <img src="/img/services/app.png" style="margin-top:8px;" > </center>
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">C</span><span style="font-size:15px">anopy One   provides timely delivered and cost-effective solutions with clear focus on high quality. Our experience in providing quality software solutions, project management capabilities and world class standards can give your business the edge on</span> 
   </p></div></br></br></br></br>
   <div class="row">
   <div class="span1">&nbsp;</div>
   <div class="span10">

<h3><i class="icon-ok icon-large cc"></i>Java/J2EE Solutions</h3>
<h3><i class="icon-ok icon-large cc"></i>.Net Solutions</h3>
<h3><i class="icon-ok icon-large cc"></i>Web and e-commerce</h3>
<h3><i class="icon-ok icon-large cc"></i>Open Source Technology</h3>

</div>
</div></div></div>


</br></br></br></br></br></br>

