<style>
body {
    
    background: #FFF;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}
.icon-large {
text-align: center;
padding-right: 8px;
}


<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/services/consulting.jpg" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">C</span><span style="font-size:15px">anopy One excels in providing strategic business consulting services through Data Warehouse, and Business Intelligence and ERP Solutions for Fortune 500 clients, small to mid-size companies as well as government clients that include the federal, state and local institutions. </span>
</br></br></br>

<span style="font-size:15px">We specialize in the following across all business and industry segments:</span>

<h3><i class="icon-arrow-right icon-large cc"></i>Enterprise data integration</h3> 
<h3><i class="icon-arrow-right icon-large cc"></i>ETL (Extract, Transform, Load)</h3>
<h3><i class="icon-arrow-right icon-large cc"></i>Business Intelligence solutions </h3>
<h3><i class="icon-arrow-right icon-large cc"></i>Data management applications </h3>
</div>
 </p>
</div></div>


</br></br></br></br></br></br>

