<style>
body {
    background: #FFF !important;
	font-size: 15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}
.icon-large {
text-align: center;
padding-right: 8px;
}


<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/services/consulting.jpg" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <span style="font-size:15px"><p>
Canopy One excels in providing strategic business consulting services through Data Warehouse, and Business Intelligence and ERP Solutions for Fortune 500 clients, small to mid-size companies as well as government clients that include the federal, state and local institutions. Canopy one is fully aware of the changing business and technology landscape over these years. The constant need to shift from traditional and legacy systems to meet the changing industry demands creates a need to bring solutions that can be developed on proven technological agility paving way for new business needs. </p>
<p>
We specialize in the following across all business and industry segments:
<ul style="margin-left:20px;">
<li class="icon-circle-arrow-right ">Enterprise data integration: </li>
<li class="icon-circle-arrow-right ">ETL (Extract, Transform, Load)</li>
<li class="icon-circle-arrow-right ">Business Intelligence solutions </li>
<li class="icon-circle-arrow-right ">Data management applications</li> 
</ul>
</p>
<p>
Enterprise applications and data integration services are constantly evolving as a result of the client's changing business needs. This demands a proven expertise in understanding data integration services to ensure sustained success to meet the future business needs. Canopy one has experience and expertise in providing data integrating services creating a successful and adaptive businesses with a robust business architecture, process transformation and innovation.
</p>
<p>

Our integrated approach can transform business processes, building application capabilities to ensure greater functionality dealing with the customers, business processes, and higher return on investments with total quality approach in the applications and technology solutions. This approach spreads across even in to   next generation technologies such as cloud computing enterprise mobility, social media or digital marketing to facilitate interactive experience defining a clear edge of client's business in online transactions.
Canopy one   experience spreads across the value chain of the businesses ranging from ERP, supply chain management, CRMs with hands on expertise in working on applications such as SAP or ORACLE applications following best practices of the industry in providing business intelligence services, data management services. 
</p>
</span>

</div>
</div></div>


</br></br></br></br></br></br></br></br></br></br></br></br>

