<style>
body {
    
    background: #FFF;
	font-size:15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/services/dw.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">D</span>ata Warehousing (DW) and Business Intelligence (BI) is the cornerstone of an organization's strategy to compete successfully in a highly competitive environment. Most organizations face the challenge of getting meaningful information from the vast amounts of data they collect on a daily basis. Canopy One possess the expertise to recommend effective strategy for Data management which includes Data Architecture, ETL, metadata and analytics. </p>
   <p>

The key to maximize Information Management investment is the adoption of the Business Intelligence (BI) layer throughout the organization. We understand that the effective deployment of the latest generation of BI tools can offer executive leadership visibility into the operation of their enterprise that can allow them to achieve their strategic goals and maximize the value they accrue from their investments. Our BI team will provide you the guidance to pick the appropriate tool and implement it successfully which will accelerate true business value and maximum Return on Investment (ROI).

 </p>
</div></div></div>


</br></br></br></br></br></br>

