<style>
body {
    
    background: #FFF;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/services/integration.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap cc">E</span>nterprise application integration is the process whereby disparate tools, off-the-shelf applications, and legacy systems are combined to address specific enterprise-wide needs - perhaps a new business process, or the consequences of a reorganization or merger. Such events typically add stress to the existing IT systems, as well as the personnel involved in the process. To leverage this, businesses need Commercial off the shelf (COTS) products that often provide the solution in terms of cost, risk and implementation time. </p>
   </br></br> </br></br> 
<p><img src="/img/inte.jpg" align="left"  height="200px" style="margin-top:-30px;"/>
<span class="dropcap">L</span>egacy applications have an unexpected long life and must continue to serve as the enterprise evolves. Integrating old and new applications usually involves writing custom code, as these components from different sources run on different platforms which were originally not designed to inter operate. Increasingly, the data feeding these solutions emanate from a wide range of sources such as: file stores, legacy applications, external partners, e-mail, and Web. Facilities are needed to recognize, manage, and transform these data sets to meet the formats imposed by the COTS products and legacy applications
 </p>
</div></div></div>


</br></br></br></br></br></br>

