<style>
body {
    
    background: #FFF;
	font-size:15px !important;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}
.well {
padding: 0px !important;
}
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
 <img src="/img/services/proffesional.png" style="margin-top:8px;" > 

   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <div class="" style="height:40px;"> &nbsp;&nbsp;<h2><i class=" icon-circle-arrow-right  "></i>&nbsp;&nbsp;Off-site/Offshore Custom Development Model</h2></div>
</br>
<p>
Canopy One handles all aspects of application development. Our U.S. resources handle the project management, requirements analysis and design disciplines. Our Hyderabad development labs manage the development, implementation, and testing deliverables. </p>
<p>
Canopy One employs a development methodology based on the industry-standard Rational Unified Process (RUP). In the inception phase, Canopy One further tailors our process to accommodate your environment. Our goal is to create a methodology that provides the proper structure for your project, without being cumbersome or bureaucratic. </p>


 <div class="" style="height:40px;"> &nbsp;&nbsp;<h2><i class=" icon-circle-arrow-right  "></i>&nbsp;&nbsp;Off-site/Offshore Hybrid Custom Development Model</h2></div></br>

This model is similar to the Off-site/Offshore Model except that some of the resources will be U.S. resources that will reside at your site during the project. They will work in conjunction with the Canopy One Project Management team and the offshore development team. All process and methodology components remain the same. 
</br></br>

 <div class="" style="height:40px;"> &nbsp;&nbsp;<h2><i class=" icon-circle-arrow-right  "></i>&nbsp;&nbsp;Off-site Dedicated Resource Model</h2></div></br>

Using this model, you manage the project and define the requirements. Your project management team directly manages our dedicated team of developers and testers. This model incorporates ongoing oversight to ensure that the team is achieving its maximum effectiveness. For longer engagements, or at your request, we rotate off-site team members to your site for a deeper view of your business and corporate culture.   
</br></br>
<div class="" style="height:40px;"> &nbsp;&nbsp;<h2><i class=" icon-circle-arrow-right  "></i>&nbsp;&nbsp;On-site Custom Development Model</h2></div></br>
With this model, Canopy One places the full development team at your location. For some projects, you may require a team to reside on-site with your teams. The Canopy One team will maintain the same level of Project Management oversight and will provide the same focus on quality and transparency in this model, through our RUP-based process.   
</br></br>
<div class="" style="height:40px;"> &nbsp;&nbsp;<h2><i class=" icon-circle-arrow-right  "></i>&nbsp;&nbsp;On-site Dedicated Resource Model</h2></div></br>
<p>For an engagement that requires a full team that you want to manage, Canopy One will assemble a team to work at your site. These resources are typically a combination of our bench resources and independent consultants who are recruited for the project. We use our screening methodology to provide you with the best-qualified independent consultants.</p>
<p>
 In this model, we will work in conjunction with our Staff Augmentation Team to provide a deeper perspective of the job position and more in-depth technical screening.  
 </p>
 
</div></div></div>


</br></br></br></br></br></br>

