<style>
body {
    
    background: #FFF;
		font-size:15px !important;

}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}
.well {
padding: 0px !important;
}


<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/services/staff.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> At Canopy One we understand the challenges of identifying and recruiting precisely the technical talent that you require. Our staff augmentation services possess real-time technology management expertise coupled with technical recruiting experience; this positions Canopy One as a true consultative partner. Our skilled professionals can help you manage the fluctuating technological needs and aggressive timelines by providing a full range of recruiting solutions that include Contract, Contract-to-Hire and Direct Hire placement services. </p>
<p></br>

With more than 50 technically certified recruiters globally we can quickly source and screen candidates for your contracting and full time needs in
</br></br>
<i class=" icon-circle-arrow-right  "></i> &nbsp;Technology Application Development</br></br>
<i class=" icon-circle-arrow-right  "></i>  &nbsp;  ERP/ CRM </br></br>
<i class=" icon-circle-arrow-right  "></i> &nbsp; DW and BI </br></br>
<i class=" icon-circle-arrow-right  "></i> &nbsp; Mobile Application Development </br></br>
<i class=" icon-circle-arrow-right  "></i>&nbsp; Network and Infrastructure </br></br>
<i class=" icon-circle-arrow-right  "></i>&nbsp; Cloud

 </p>
</div></div></div>


</br></br></br></br></br></br>

