<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Login - Jameen Admin</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"> 
    
<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />

<link href="/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
    
<link href="/css/admin/base-admin.css" rel="stylesheet" type="text/css">
<link href="/css/admin/pages/signin.css" rel="stylesheet" type="text/css">

</head>

<body>
	
	<div class="navbar navbar-fixed-top">
	
	<div class="navbar-inner">
		
		<div class="container">
			
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			
			<a class="brand" href="./">
				Jameen Admin				
			</a>		
			
			<div class="nav-collapse">
				<ul class="nav pull-right">
					
					<li class="">						
						Help
					</li>
					
					<li class="">						

					</li>
				</ul>
				
			</div><!--/.nav-collapse -->	
	
		</div> <!-- /container -->
		
	</div> <!-- /navbar-inner -->
	
</div> <!-- /navbar -->



<?php if($this->error):?>
<center><h2 class="alert-error"><?php echo Zend_Registry::get('Translate')->translate($this->error);?></h2></center>
<?php endif;?>


<div class="account-container">
	
	<div class="content clearfix">
		
		<form method="post">
		
			<h1>Sign In</h1>		
			
			<div class="login-fields">
				
				<p>Sign in using admin account:</p>
				
				<div class="field">
					<label for="username"><?php echo Zend_Registry::get('Translate')->translate('username'); ?>:</label>
					<input type="text" id="email" name="email" value="<?php echo $this->email?>" placeholder="Username" class="login username-field" />
				</div> <!-- /field -->
				
				<div class="field">
					<label for="password"><?php echo Zend_Registry::get('Translate')->translate('password'); ?>:</label>
					<input type="password" id="password" name="password" value="<?php echo $this->password?>" placeholder="Password" class="login password-field"/>
				</div> <!-- /password -->
				
			</div> <!-- /login-fields -->
			
			<div class="login-actions">
				
				<span class="login-checkbox">
					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />
					<label class="choice" for="Field"><?php echo Zend_Registry::get('Translate')->translate('keepMeSignedIn'); ?></label>
				</span>
									
				<button class="button btn btn-warning btn-large"><?php echo Zend_Registry::get('Translate')->translate('signin'); ?></button>
				
			</div> <!-- .actions -->
			
			
		</form>
		
	</div> <!-- /content -->
	
</div> <!-- /account-container -->


<!-- Text Under Box -->
<div class="login-extra">
	Remind <a href="#">Password</a>
</div> <!-- /login-extra -->


<script src="/js/jquery-1.7.2.min.js"></script>
<script src="/js/bootstrap.js"></script>


</body>
</html>
