<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle('CanopyOne');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Project" />
<meta name="keywords" content="Search Tutor" />
<?php echo $this->headMeta(); ?><?php echo $this->headTitle(); ?><?php echo $this->headLink() ?><?php echo $this->headStyle() ?>
<script src="/js/jquery-1.8.2.js"></script>
<script src="/js/bootstrap.js"></script>
<script  src="/js/bootstrap-carousel.js"></script>
<script  src="/js/jquery.typist.js"></script>

<!-- start: CSS -->
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/bootstrap-responsive.css" rel="stylesheet">
<link href="/css/style2.css" rel="stylesheet">
<link href="/css/font-awesome.css" rel="stylesheet">
<!--[if IE 7]>
  <link rel="stylesheet" href="http://fortawesome.github.com/Font-Awesome/assets/css/font-awesome-ie7.css">
<![endif]-->
<link href="/css/my.css" rel="stylesheet">
<!-- end: CSS -->
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<?php echo $this->headScript() ?>
</head>
    <body style="-webkit-transition: top 1s ease; " onkeydown="null">

<!--start: Header -->
<header>
            <div style="background:#2E2E2E;height:19px;border-bottom:2px solid #f06921;">
              <div class="container">
                <div class="row">
                  <div class="span10">&nbsp;</div>
                  <div class="span2">
                   
                  <a class="aa" href=""><i class="icon-map-marker"></i>&nbsp;India</a> &nbsp;&nbsp;|&nbsp;&nbsp;
                  <a class="aa" href=""><i class="icon-map-marker"></i>&nbsp;Canada</a></div> 
                </div>
                </div>

            </div>
            <!--start: Container -->
            <div class="container"> 
                
                <!--start: Row -->
                <div class="row"> 
                            <!--start: Logo -->
                        <a href="/">    <div class="logo span2" style="padding-right:6%;"> </div></a>
                            <!--end: Logo --> 
                            
                            <!--start: Navigation -->
                            <div class="span7">
                                <div class="navbar navbar-inverse">
                                            <div class="navbar-inner innn"> <a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
                                                <div class="nav-collapse collapse" style="height: 0px; ">
                                                            <ul class="nav nish">
                                                                <li id="about11" ><a href="#">ABOUT</a></li>
                                                                <li id="offer"><a href="#">SERVICES</a></li>
                                                                <li id="industry"> <a href="#">SOLUTION</a></li>
                                                                <li id="career"><a href="#">CAREERS</a></li>
                                                                <li id="contact"><a href="#">CONTACT</a></li>
                                                        </ul>
                                                    </div>
                                        </div>
                                    </div>
                        </div>
                            <!--end: Navigation --> 
                            <div class="span2 sign" style="margin-top:35px;"> 
                                     <div class="social-networking-icons pull-right"><a href="/"><img src="/img/home.png" /></a> <a href="http://www.facebook.com/" target="_blank" class="facebook tooltips" rel="tooltip" data-original-title="Facebook">Facebook</a> <a href="http://www.twitter.com/" target="_blank" class="twitter tooltips" rel="tooltip" data-original-title="Twitter">Twitter</a> <a href="http://youtube.com/" target="_blank" class="youtube tooltips" rel="tooltip" data-original-title="Youtube">Youtube</a> <a href="http://linkedin.com/" target="_blank" class="linkedin tooltips" rel="tooltip" data-original-title="Linkedin">linkedin</a> </div>

                            <!-- <a href="#myModal" role="button" class="btn" data-toggle="modal"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</a> -->
                            </div>
                    </div>
                <!--end: Row --> 
                
        </div>
            <!--end: Container--> 
            
    </header>
<!--end: Header--> 
<!-- sub menu-->
<div class="sub-nav" id="sub">
            <div class="container">
                <div class="row">
                         <div class="span2">&nbsp;</div>
                            <div class="span10 drop">
                               <a href="/about/overview">  Canopy one overview </a>&nbsp; |&nbsp;
                               <a href="/about/core"> Core Management Team </a> &nbsp; |&nbsp;
                               <a href="/about/social"> Corporate Social Responsibility</a> &nbsp; |&nbsp;
                               <a href="/about/news">News & Events </a> 
                              
                           </div>
                         </div>
        		   </div>
    			</div>
   </div>
   <div class="sub-nav" id="sub1">
            <div class="container">
                <div class="row">
                         <div class="span2">&nbsp;</div>
                            <div class="span10 drop">
                               <a href=""> Integrating services </a>&nbsp; |&nbsp;
                               <a href=""> Dw & Bi </a> &nbsp; |&nbsp;
                               <a href=""> Business consulting </a> &nbsp; |&nbsp;
                               <a href=""> Cloud services </a> &nbsp; |&nbsp;
                               <a href=""> Corporate Social Responsibility </a> &nbsp; |&nbsp;
                               <a href=""> Medical solutions </a> &nbsp; |&nbsp;
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>
<div class="sub-nav" id="sub2">
            <div class="container">
                <div class="row">
                         <div class="span2 drop">&nbsp;</div>
                            <div class="span10 drop">
                               <a href="">  Banking & finance sector </a>&nbsp; |&nbsp;
                               <a href=""> Retail market sector </a> &nbsp; |&nbsp;
                               <a href=""> Insurance sector </a> &nbsp; |&nbsp;
                               <a href=""> Health Care Sector </a> &nbsp; |&nbsp;
                               <a href=""> Transport sector </a> &nbsp; |&nbsp;
                               <a href=""> Innovation </a> 
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>
<div class="sub-nav" id="sub3">
            <div class="container">
                <div class="row">
                         <div class="span2">&nbsp;</div>
                            <div class="span10 drop">
                               <a href="">  Career Advancement Training Programme </a>&nbsp; |&nbsp;
                               <a href=""> Employment & Career </a> 
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>
<div class="sub-nav" id="sub4">
            <div class="container">
                <div class="row">
                         <div class="span2">&nbsp;</div>
                            <div class="span10 drop">

                        <a href=""> Job seekers registration </a>&nbsp; |&nbsp;
                               <a href="">Vendor registration  </a> &nbsp; |&nbsp;
                               <a href=""> Contact us & Email </a> 
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>

<!-- end sub menu --> 

<?php echo $this->layout()->content; ?> 

<!-- start: Footer -->

<div class="container-footer">
<div class="container">
            <div class="row">
                <div class="span6" style="margin-top:6px;">
                            <p>All rights reserved. 2012 CanopyOne</p>
                    </div>
                <div class="span6">
                
                           <!-- <div class="social-networking-icons pull-right"> <a href="http://www.facebook.com/" target="_blank" class="facebook tooltips" rel="tooltip" data-original-title="Facebook">Facebook</a> <a href="http://www.twitter.com/" target="_blank" class="twitter tooltips" rel="tooltip" data-original-title="Twitter">Twitter</a> <a href="http://youtube.com/" target="_blank" class="youtube tooltips" rel="tooltip" data-original-title="Youtube">Youtube</a> <a href="http://linkedin.com/" target="_blank" class="linkedin tooltips" rel="tooltip" data-original-title="Linkedin">linkedin</a> </div>
                    -->
                    </div>
        </div>
    </div>
</div>
<!-- end Container -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> My CanopyOne Login </h3>
  </div>
  <div class="modal-body">
    <p>
    <div class="row">
			<div class="login-content span4 mod">
				
				<form class="well">
					<label>Username</label>
					<input type="text" placeholder="Type something…" class="input">
					<label>Password</label>
					<input type="text" placeholder="Type something…" class="input">

					<label class="checkbox">
				    	<input type="checkbox"> Remember Password
					</label>
				  	<a class="btn btn-info" type="submit" href="index.html">Log in</a>
				  	
				</form>	
			</div>
		<div>
	</div>
</div>
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary">Sign Up</button>
  </div>
</div>










</body>
    </html><script type="application/javascript">
	 $("#sub").hide();
	 $("#sub1").hide();
	 $("#sub2").hide();
	 $("#sub3").hide();
	 $("#sub4").hide();

				 //$("#basic").removeClass("active");
	 $("#about11").click(function(){
								 $("#about11").addClass("active");
								 $("ul.nish > li:gt(0)").removeClass("active");
								 $("#sub").toggle();
								 $("#sub1").hide();
								 $("#sub2").hide();
								 $("#sub3").hide();
								 $("#sub4").hide();
								 }) 
	 $("#offer").click(function(){
		                         $("ul.nish > li:lt(1)").removeClass("active");
								 $("#offer").addClass("active");
								 $("ul.nish > li:gt(1)").removeClass("active");
								 $("#sub1").toggle();
								 	 $("#sub").hide();
									 $("#sub2").hide();
									 $("#sub3").hide();
									 $("#sub4").hide();
								
								 })
    $("#industry").click(function(){
		                         $("ul.nish > li:lt(2)").removeClass("active");
								 $("#industry").addClass("active");
								 $("ul.nish > li:gt(2)").removeClass("active");
								 $("#sub2").toggle();
								 	 $("#sub").hide();
									 $("#sub1").hide();
									 $("#sub3").hide();
									 $("#sub4").hide();

								 })

   $("#career").click (function(){
		                         $("ul.nish > li:lt(3)").removeClass("active");
								 $("#career").addClass("active");
								 $("ul.nish > li:gt(3)").removeClass("active");
								 $("#sub3").toggle();
								 	 $("#sub").hide();
									 $("#sub1").hide();
									 $("#sub2").hide();
									 $("#sub4").hide();

								 })

    $("#contact").click(function(){
		                         $("ul.nish > li:lt(4)").removeClass("active");
								 $("#contact").addClass("active");
								 $("ul.nish > li:gt(4)").removeClass("active");
								 $("#sub4").show();
								 	 $("#sub").hide();
									 $("#sub1").hide();
									 $("#sub2").hide();
									 $("#sub3").hide();

								 })



    $('.carousel').carousel({
    interval: 5000,
	 //auto: 4000,
     fade: 400,

    })
	 
    </script>