<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle('CanopyOne');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Project" />
<meta name="keywords" content="Search Tutor" />
<?php echo $this->headMeta(); ?><?php echo $this->headTitle(); ?><?php echo $this->headLink() ?><?php echo $this->headStyle() ?>
<script src="/js/jquery-1.8.2.js"></script>
<script src="/js/bootstrap.js"></script>
<script  src="/js/bootstrap-carousel.js"></script>
<script  src="/js/jquery.typist.js"></script>

<!-- start: CSS -->
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/bootstrap-responsive.css" rel="stylesheet">
<link href="/css/style2.css" rel="stylesheet">
<link href="/css/font-awesome.css" rel="stylesheet">
<!--[if IE 7]>
  <link rel="stylesheet" href="http://fortawesome.github.com/Font-Awesome/assets/css/font-awesome-ie7.css">
<![endif]-->
<link href="/css/my.css" rel="stylesheet">
<!-- end: CSS -->
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<?php echo $this->headScript() ?>
</head>
    <body style="-webkit-transition: top 1s ease; " onkeydown="null">

<!--start: Header -->
<header>
            <div style="background:#2E2E2E;height:19px;border-bottom:2px solid #f06921;">
              <div class="container">
                <div class="row">
                  <div class="span10">&nbsp;</div>
                  <div class="span2">
                   
                  <a class="aa" href=""><i class="icon-map-marker"></i>&nbsp;India</a> &nbsp;&nbsp;|&nbsp;&nbsp;
                  <a class="aa" href=""><i class="icon-map-marker"></i>&nbsp;Canada</a></div> 
                </div>
                </div>

            </div>
            <!--start: Container -->
            <div class="container"> 
                
                <!--start: Row -->
                <div class="row"> 
                            <!--start: Logo -->
                        <a href="/">    <div class="logo span2" style="padding-right:6%;"> </div></a>
                            <!--end: Logo --> 
                            
                            <!--start: Navigation -->
                            <div class="span7">
                                <div class="navbar navbar-inverse">
                                            <div class="navbar-inner innn"> <a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
                                                <div class="nav-collapse collapse" style="height: 0px; ">
                                                            <ul class="nav nish">
                                                                <li id="home"><a href="/"><i id="home1" class="icon-home" style="font-size:28px;"></i></a></li>
                                                                <li id="about11" ><a href="#"><font id="a"><b>ABOUT</b></font></a></li>
                                                                <li id="offer"><a href="#" ><font id="b"><b>SERVICES</b></font></a></li>
                                                                <li id="industry"> <a href="#" ><font id="c"><b>SOLUTIONS</b></font></a></li>
                                                                <li id="career"><a href="#" ><font id="d"><b>CAREERS</b></font></a></li>
                                                                <li id="contact"><a href="#" ><font id="e"><b>CONTACT</b></font></a></li>
                                                        </ul>
                                                    </div>
                                        </div>
                                    </div>
                        </div>
                            <!--end: Navigation --> 
                            <div class="span2 sign" style="margin-top:35px;"> 
                                     <div class="social-networking-icons pull-right"><a href="#email" role="button" data-toggle="modal" class="home tooltips" rel="tooltip" data-original-title="email"><img src="/img/home.png" /></a>
                                      <a href="http://www.facebook.com/pages/Canopy-One-Solutions/125589714209413" target="_blank" class="facebook tooltips" rel="tooltip" data-original-title="Facebook">Facebook</a> 
                                     <a href="http://twitter.com/CanopyOne" target="_blank" class="twitter tooltips" rel="tooltip" data-original-title="Twitter">Twitter</a> <a href="http://youtube.com/" target="_blank" class="youtube tooltips" rel="tooltip" data-original-title="Youtube">Youtube</a> <a href="http://www.linkedin.com/company/canopy-one-solutions-inc" target="_blank" class="linkedin tooltips" rel="tooltip" data-original-title="Linkedin">linkedin</a> </div>

                            <!-- <a href="#myModal" role="button" class="btn" data-toggle="modal"><i class="icon-external-link"></i>&nbsp;&nbsp;My CanopyOne Login</a> -->
                            </div>
                    </div>
                <!--end: Row --> 
                
        </div>
            <!--end: Container--> 
            
    </header>
<!--end: Header--> 
<!-- sub menu-->
<div class="sub-nav" id="sub">
            <div class="container">
                <div class="row">
                         <div class="span2">&nbsp;</div>
                            <div class="span10 drop">
                               <a href="/about/overview"> <font id="a1" > Who We are</font> </a>&nbsp; |&nbsp;
                               <a href="/about/differentiators"><font id="a2"> Our Differentiators</font> </a> &nbsp; |&nbsp;
                               <a href="/about/core"><font id="a3"> Leadership Team </font></a> &nbsp; |&nbsp;
                               <a href="/about/alliances"><font id="a4"> Alliances </font></a> &nbsp; |&nbsp;
                               <a href="/about/social"><font id="a5"> Corporate Social Responsibility</font> </a> &nbsp; |&nbsp;
                               <a href="/about/news"><font id="a6">News & Events </font></a> 
                              
                           </div>
                         </div>
        		   </div>
    			</div>
   </div>
   <div class="sub-nav" id="sub1">
            <div class="container">
                <div class="row">
                         <div class="span2">&nbsp;</div>
                            <div class="span10 drop">
                               <a href="/services/integration"> <font id="b1">Integration Services</font> </a>&nbsp; |&nbsp;
                               <a href="/services/application"><font id="b2"> Application Services</font> </a>&nbsp; |&nbsp;
                               <a href="/services/dw"><font id="b3"> DW & BI Services</font> </a> &nbsp; |&nbsp;
                               <a href="/services/consulting"><font id="b4"> Consulting Services</font> </a> &nbsp; |&nbsp;
                               <a href="/services/professional"><font id="b5"> Professional Services</font> </a> &nbsp; |&nbsp;
                               <a href="/services/staff"> <font id="b6">Staff Augmentation Services</font> </a> 
                               
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>
<div class="sub-nav" id="sub2">
            <div class="container">
                <div class="row">
                         <div class="span2 drop">&nbsp;</div>
                            <div class="span10 drop">
                               <a href="/solution/health"> <font id="c1"> Health Care </font></a>&nbsp; |&nbsp;
                               <a href="/solution/finance"><font id="c2"> Finance</font> </a> &nbsp; |&nbsp;
                               <a href="/solution/telecom"> <font id="c3">Telecom </font></a> &nbsp; |&nbsp;
                               <a href="/solution/logistics"><font id="c4"> Logistics</font> </a> &nbsp; |&nbsp;
                               <a href="/solution/energy"><font id="c5"> Energy </font></a> &nbsp; |&nbsp;
                               <a href="/solution/manufacturing"> <font id="c5">Retail </font></a> 
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>
<div class="sub-nav" id="sub3">
            <div class="container">
                <div class="row">
                         <div class="span3">&nbsp;</div>
                            <div class="span9 drop">
                               <a href="/careers/culture"> <font id="d1"> Our Culture</font> </a>&nbsp; |&nbsp;
                               <a href="/careers/current"> <font id="d2"> Current Openings</font> </a>&nbsp; |&nbsp;
                               <a href="/careers/applicants"><font id="d3"> New Applicants </font></a> 
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>
<div class="sub-nav" id="sub4">
            <div class="container">
                <div class="row">
                         <div class="span4">&nbsp;</div>
                            <div class="span8 drop">

                        
                               <a href="/contact/vendor"><font id="e1">Vendor Registration </font> </a> &nbsp; |&nbsp;
                               <a href="/contact/locations"><font id="e2">Locations </font></a> 
                            </div>
                         </div>
        		   </div>
    			</div>
   </div>

<!-- end sub menu --> 

<?php echo $this->layout()->content; ?> 

<!-- start: Footer -->

<div class="container-footer">
<div class="container">
            <div class="row">
                <div class="span6" style="margin-top:6px;">
                            <p>All rights reserved. 2012 CanopyOne</p>
                    </div>
                <div class="span6">
                
                           <!-- <div class="social-networking-icons pull-right"> <a href="http://www.facebook.com/" target="_blank" class="facebook tooltips" rel="tooltip" data-original-title="Facebook">Facebook</a> <a href="http://www.twitter.com/" target="_blank" class="twitter tooltips" rel="tooltip" data-original-title="Twitter">Twitter</a> <a href="http://youtube.com/" target="_blank" class="youtube tooltips" rel="tooltip" data-original-title="Youtube">Youtube</a> <a href="http://linkedin.com/" target="_blank" class="linkedin tooltips" rel="tooltip" data-original-title="Linkedin">linkedin</a> </div>
                    -->
                    </div>
        </div>
    </div>
</div>
<!-- end Container -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> My CanopyOne Login </h3>
  </div>
  <div class="modal-body">
    <p>
    <div class="row">
			<div class="login-content span4 mod">
				
				<form class="well">
					<label>Username</label>
					<input type="text" placeholder="Type something…" class="input">
					<label>Password</label>
					<input type="text" placeholder="Type something…" class="input">

					<label class="checkbox">
				    	<input type="checkbox"> Remember Password
					</label>
				  	<a class="btn btn-info" type="submit" href="index.html">Log in</a>
				  	
				</form>	
			</div>
		<div>
	</div>
</div>
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary">Sign Up</button>
  </div>
</div>
<!-- email --->
<div id="email" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>
    
    <form name="contactform" method="post" action="send_form_email.php">
<table width="450px">
<tbody>
<tr>
<td valign="top"><label for="first_name">First Name * </font></label></td>
<td valign="top"><input type="text" name="first_name" maxlength="50" size="30" /></td></tr>
<tr>
<td valign="top"><label for="last_name">Last Name *</font></label></td>
<td valign="top"><input type="text" name="last_name" maxlength="50" size="30" /></td></tr>
<tr>
<td valign="top"><label for="email">Email Address *</font></label></td>
<td valign="top"><input type="text" name="email" maxlength="80" size="30" /></td></tr>
<tr>
<td valign="top"><label for="telephone">Telephone Number</font></label></td>
<td valign="top"><input type="text" name="telephone" maxlength="30" size="30" /></td></tr>
<tr>
<td valign="top"><label for=" comments ">Message *</font></label></td>
<td valign="top"><textarea name="comments" maxlength="1000" cols="25" rows="6"></textarea></td></tr>
<tr>
<td colspan="2" style="text-align: center">   </td></tr></tbody></table></form>
    
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <input type="submit" class="btn btn-primary" value="submit">
  </div>
</div>
<!-- end email model -->



</body>
    </html>
<script  src="/js/my.js"></script>
	<script type="application/javascript">
	 
    </script>