<style>
.big-intro {
	font-size: 24px;
	line-height: 1.7em;
	color: #888;
	padding: 25px 0;
	font-family: 'Alegreya SC', serif;
	border: 1px dotted #CF6;
	border-right: none;
	border-left: none;
}
.slash {
	padding-right: .25em;
	color: #C00;
}
.nis1 {
	line-height: 27px !important;
	font-size: 188x;
	font-weight: bold;
}
#subpage {
	margin-top: 3em;
	margin-bottom: 2.5em;
}
.about-intro {
	color: #333;
	font-size: 14px;
	margin: 0 0 80px;
}
.about-intro h4 {
	margin: 0 0 20px;
}
.team-member {
	background: #fff;
	border: 2px solid #C9C;
	border-bottom: 3px solid #ffd800;
	margin-bottom: 30px;
 -webkit-transition: border .2s ease-out;
 -moz-transition: border .2s ease-out;
 -ie-transition: border .2s ease-out;
 -o-transition: border .2s ease-out;
 transition: border .2s ease-out;
}
.team-member:hover {
	border-bottom: 3px solid #d73300;
}
.member-photo img {
	display: block;
	width: 100%;
}
.member-info {
	display: block;
	padding: 16px 15px 9px;
}
.member-info h4 {
	color: #d73300;
	margin: 0;
}
.member-info .position {
	color: #959595;
	display: block;
	margin-bottom: 15px;
}
.member-info p {
	border-bottom: 1px dotted #d9d9d9;
	border-top: 1px dotted #d9d9d9;
	margin: 10px 0;
	padding: 20px 0;
}
.member-social-links {
	display: inline-block;
	margin: 0;
}
.member-social-links li {
	display: block;
	float: left;
}
.member-social-links a {
	color: #959595;
	font-size: 12px;
	letter-spacing: 1px;
	margin-right: 10px;
	text-transform: uppercase;
}
.member-social-links a:hover {
	color: #d73300;
}
.dropcap {
	font-family: Georgia, serif;
	font-size: 55px;
	color:#f06921;
	padding: 0 7px 5px 0;
	line-height: 1em;
	float: left;
	text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.dropcapsmall {
	font-family: Georgia, serif;
	font-size: 20px;
	color:#f06921;
	opacity:0.6;
	padding: 0 7px 5px 0;
	margin-top:3px;
	line-height: 1em;
	float: left;
	text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
	font-size: 24px;
	color:#000;
	text-decoration : underline;
}
.comment-title {
	color: #333;
	font-size: 19px;
	text-transform: uppercase;
	line-height: 0;
	margin-bottom: 25px;
	margin-top:50px;
}
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}
.hero-unit h1 {
	background: url("../img/h.png") no-repeat scroll center top transparent;
	color: #7B0202;
	font-family: 'Lobster', cursive;
	font-size: 22px;
	font-weight: normal;
	margin: 25px 0;
	padding-right: 10px;
	text-align: center;
	text-transform: capitalize;
}
</style>

<div class="coretop">
        <div class="container" >
                <div class="row" >
                        <div class="span12" > <img src="/img/alliances.png" style="margin-top:8px;" > </div>
                </div>
        </div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
        <div class="row">
                <div class="span12" style="text-align:justify;margin-top:20px;">
                        <p> Partnering up with renowned firms from across the globe has enabled us to offer fully-integrated world class solutions to our clientele. Our alliances are based on mutual understanding and trust, sharing the same principles in business ethics with our partners, an attribute that has proven to be a strong competitive advantage for Canopy One Solutions over the years. </p>
                </div>
        </div>
        </br></br></br>
        <div class="row">
        
        
                  <div class="span12" style="text-align:justify;">
                 <ul style="margin-left:22px">
                 <li class="icon-circle-arrow-right">Canopy One has signed partnership agreement with <font color="#f06921">Pitney Bowes Inc</font> to market / train / and to provide support services to the clients of PBS Inc<img src="/img/pb.jpg"   style="margin-left:30px;margin-top:-20px;height:50px;width:100px"/> </li>

                 <li class="icon-circle-arrow-right">Canopy one works closely with <font color="#f06921">Texas AM University</font> and <font color="#f06921">university of Virginia</font>
in various career advancement programs</li></ul></div>

        </div>
        </br></br></br></br></br>
        </p>
        </br>
</div>

