<link href='http://fonts.googleapis.com/css?family=Port+Lligat+Slab' rel='stylesheet' type='text/css'>
<style>
.about-intro {
    color: #333;
    font-size: 14px;
    margin: 0 0 80px;
}
.about-intro h4 {
    margin: 0 0 20px;
}
.team-member {
    background: #fff;
    border: 2px solid #C9C;
    border-bottom: 3px solid #ffd800;
    margin-bottom: 30px;
    -webkit-transition: border .2s ease-out;
    -moz-transition: border .2s ease-out;
    -ie-transition: border .2s ease-out;
    -o-transition: border .2s ease-out;
    transition: border .2s ease-out;
}
.team-member:hover {
    border-bottom: 3px solid #d73300;
}
.member-photo img {
    display: block;
    width: 100%;
}
.member-info {
    display: block;
    padding: 16px 15px 9px;
}
.member-info h4 {
    color: #d73300;
    margin: 0;
}
.member-info .position {
    color: #959595;
    display: block;
    margin-bottom: 15px;
}
.member-info p {
    border-bottom: 1px dotted #d9d9d9;
    border-top: 1px dotted #d9d9d9;
    margin: 10px 0;
    padding: 20px 0;
}
.member-social-links {
    display: inline-block;
    margin: 0;
}
.member-social-links li {
    display: block;
    float: left;
}
.member-social-links a {
    color: #959595;
    font-size: 12px;
    letter-spacing: 1px;
    margin-right: 10px;
    text-transform: uppercase;
}
.member-social-links a:hover {
    color: #d73300;
}
.dropcap {
    font-family: Georgia, serif;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
    
    font-size: 18px;
	color:#000;
    text-shadow: 1px 1px 0 #fafafa, 1px 1px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.comment-title {
    color: #333;
    font-size: 19px;
    text-transform: uppercase;
    line-height: 0;
    margin-bottom: 25px;
	margin-top:50px;
}  
body {
    #font-family:'Arial';
    background:  url(/img/b.png) repeat;
}
.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 10px;
    text-align: center;
    text-transform: capitalize;
}
.newfont{
	font-family: 'Port Lligat Slab', serif;
	border-bottom:#C33 dotted 2px;
}
.newfont2{
 font: 13px/1.7em 'Open Sans';
font-family: 'Open Sans';
font-size: 18px;
font-style: normal;
font-variant: normal;
font-weight: normal;
line-height: 1.3em;
text-align:justify;

}

</style>


<!--
<div class="container-footer" style="background:url('/img/wave.png') repeat; height:50px;">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
                CANOPY ONE OVERVIEW
                    </div>
        </div>
    </div>
</div>
-->
<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12">
     <img src="/img/image4.jpg" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>


<div class="container">
                   <div class="row">
		<div class="span10 hero-unit offset1">
			<h1>Meet Our Team</h1>
		</div></div>
        <div class="row">

   <div class="span3">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/core/mr_gopal.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Mr. Gopal Bethi</h4>
                            <span class="position">President / CEO</span>
                            <p>Mr. Gopal Bethi founder and President of Canopy One Solutions established this firm with a vision to provide knowledge sharing center facilitating various resources to IT companies. Canopy One Solutions under his leadership and vision has achieved exponential growth right from its inception.
                          <a href="#gopal"   data-toggle="modal" style="color:#933"> Read more </a>
                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/core/mr_raman.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Raman V Machiraju</h4>
                            <span class="position">...........</span>
                            <p>Raman V Machiraju has rich experience for more than 29 years of Successful Career in Project Management working in different segments on IT solutions for finance / Health Care and Security Projects in India. His Wide understanding of the field and rich experience 
                                                      <a href="#raman"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                                <li><a href=""><i class=" icon-facebook"></i></a></li>
                                <li><a href=""><i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/core/dawn.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Dawn Reames</h4>
                            <span class="position">......</span>
                            <p>Dawn Reams has joined Canopy One right from its inceptions and has been key associate of founder members. She has been facilitating financial, recruitment, Immigration processes of the company. Her commitment and dedication to help the ambitious IT consultants to secure 
                                                      <a href="#dawn"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>


                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/author_1.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Kiran Thuraga</h4>
                            <span class="position">.........</span>
                            <p>Kiran Thuraga is an IT professional with wide experience in providing cost effective solutions working with best IT firms. He is presently heading the India operations. Kiran has been a key member of the organization in establishing a full-fledged IT center with development and training
                                                      <a href="#kiran"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>


                            </ul>
                        </div>
                    </div>
                </div>

   </div>
    </div>
    </div>
   
    
    
    
<!-- Mr. Gopal Read More --> 
<div id="gopal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> Mr. Gopal Bethi </h3>
  </div>
  <div class="modal-body" style="text-align:justify;">
  <p >Mr. Gopal Bethi founder and President of Canopy One Solutions established this firm with a vision to provide knowledge sharing center facilitating various resources to IT companies. Canopy One Solutions under his leadership and vision has achieved exponential growth right from its inception.</p>
    <p>Mr. Gopal Bethi has more than 13 years of experience in diverse technology environments, most of which on mission critical solutions in full lifecycle of Data warehousing and Business Intelligence applications. His Expertise in analysis, design, development and implementation of Data Warehouse and Data marts in Telecom, Insurance and Financial Industries has helped to build innovative solutions suiting the client's needs.</p>
    <div class="row">
			<div class="login-content span4 mod">
			</div>
		<div>
	</div>
</div>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>


<!-- Mr. Raman Read More --> 
<div id="raman" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> Raman V Machiraju </h3>
  </div>
  <div class="modal-body" style="text-align:justify;">
  <p >Raman V Machiraju has rich experience for more than 29 years of Successful Career in Project Management working in different segments on IT solutions for finance / Health Care and Security Projects in India. His Wide understanding of the field and rich experience in the corporate sector is coupled with hands on experience in Information Technology and Health care segments.</p><p>
He has an excellent experience working on healthcare and insurance industries. 
He attended national & International   forums   on ICT / Development / Business summits and presented Papers on Tele centers at an International e-Asia conference. He also gave a presentation at Humanitarian Center Cambridge on microenterprise.</p>
    <div class="row">
			<div class="login-content span4 mod">
			</div>
		<div>
	</div>
</div>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>
   
<!-- Dawn Reames Read More --> 
<div id="dawn" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> Dawn Reames </h3>
  </div>
  <div class="modal-body" style="text-align:justify;">
  <p >Dawn Reams has joined Canopy One right from its inceptions and has been key associate of founder members. She has been facilitating financial, recruitment, Immigration processes of the company. Her commitment and dedication to help the ambitious IT consultants to secure a good assignment and build their career is well proven.. Dawn has been instrumental in building Canopy One and her tireless efforts at all times has been a valued contribution for the organization
</p>
    <div class="row">
			<div class="login-content span4 mod">
			</div>
		<div>
	</div>
</div>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>
<!-- Mr. Kiran Read More --> 
<div id="kiran" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> Kiran Thuraga</h3>
  </div>
  <div class="modal-body" style="text-align:justify;">
  <p >Kiran Thuraga is an IT professional with wide experience in providing cost effective solutions working with best IT firms. He is presently heading the India operations. Kiran has been a key member of the organization in establishing a full-fledged IT center with development and training & development resource center for Canopy one.
</p>
    <div class="row">
			<div class="login-content span4 mod">
			</div>
		<div>
	</div>
</div>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>
   

   
    
    
    
    
    <!-- Modal -->
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> Mr... </h3>
  </div>
  <div class="modal-body">
    <p>
    <div class="row">
			<div class="login-content span4 mod">
				
			</div>
		<div>
	</div>
</div>
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary"></button>
  </div>
</div>

