<link href='http://fonts.googleapis.com/css?family=Port+Lligat+Slab' rel='stylesheet' type='text/css'>
<style>
.about-intro {
	color: #333;
	font-size: 14px;
	margin: 0 0 80px;
}
.about-intro h4 {
	margin: 0 0 20px;
}
.team-member {
	background: #fff;
	border: 2px solid #C9C;
	border-bottom: 3px solid #ffd800;
	margin-bottom: 30px;
 -webkit-transition: border .2s ease-out;
 -moz-transition: border .2s ease-out;
 -ie-transition: border .2s ease-out;
 -o-transition: border .2s ease-out;
 transition: border .2s ease-out;
}
.team-member:hover {
	border-bottom: 3px solid #d73300;
}
.member-photo img {
	display: block;
	width: 100%;
}
.member-info {
	display: block;
	padding: 16px 15px 9px;
}
.member-info h4 {
	color: #d73300;
	margin: 0;
}
.member-info .position {
	color: #959595;
	display: block;
	margin-bottom: 15px;
}
.member-info p {
	border-bottom: 1px dotted #d9d9d9;
	border-top: 1px dotted #d9d9d9;
	margin: 10px 0;
	padding: 20px 0;
}
.member-social-links {
	display: inline-block;
	margin: 0;
}
.member-social-links li {
	display: block;
	float: left;
}
.member-social-links a {
	color: #959595;
	font-size: 12px;
	letter-spacing: 1px;
	margin-right: 10px;
	text-transform: uppercase;
}
.member-social-links a:hover {
	color: #d73300;
}
.dropcap {
	font-family: Georgia, serif;
	font-size: 55px;
	padding: 0 7px 5px 0;
	line-height: 1em;
	float: left;
	text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
	font-size: 18px;
	color:#000;
	text-shadow: 1px 1px 0 #fafafa, 1px 1px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.comment-title {
	color: #333;
	font-size: 19px;
	text-transform: uppercase;
	line-height: 0;
	margin-bottom: 25px;
	margin-top:50px;
}
body {
 #font-family:'Arial';
	background:  url(/img/b.png) repeat;
}
.hero-unit h1 {
	color: #7B0202;
	font-family: 'Lobster', cursive;
	font-size: 28px;
	font-weight: normal;
	margin: 25px 0;
	text-align: left;
	text-transform: capitalize;
}
.newfont {
	font-family: 'Port Lligat Slab', serif;
	border-bottom:#C33 dotted 2px;
}
.newfont2 {
	font: 13px/1.7em 'Open Sans';
	font-family: 'Open Sans';
	font-size: 18px;
	font-style: normal;
	font-variant: normal;
	font-weight: normal;
	line-height: 1.3em;
	text-align:justify;
}
</style>

<!--
<div class="container-footer" style="background:url('/img/wave.png') repeat; height:50px;">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
                CANOPY ONE OVERVIEW
                    </div>
        </div>
    </div>
</div>
-->
<div class="coretop">
        <div class="container" >
                <div class="row" >
                        <div class="span12"> <img src="/img/image4.jpg" style="margin-top:8px;" > </div>
                </div>
        </div>
</div>
<div class="container">
        <div class="row">
                <div class="span12 hero-unit ">
                        <h1 class="head">Meet Our Team</h1>
                </div>
        </div>
        <div class="row">
                <div class="span9">
                        <div class="team-member">
                                <div class="member-info">
                                        <h4>Mr. Gopal Bethi</h4>
                                        <span class="position">President</span>
                                        <p>Mr. Gopal Bethi founder and President of Canopy One Solutions established this firm with a vision to provide
                                                innovative cost effective IT solutions and collaborative engagement models that help clients  across the globe  and  align their  strategy with business goals. Canopy One Solutions under his leadership and vision has achieved exponential growth right from its inception.  Mr. Gopal Bethi has more than 15 years of experience in diverse technology environments in Telecom, Insurance and Financial Industries. He played a key role for several  mission critical solutions for Canopy One's clients especially in the area of Data warehousing and Business Intelligence. </p>
                                        <ul class="member-social-links">
                                                <li><a href=""><i class=" icon-facebook"></i></a></li>
                                                <li><a href=""><i class="  icon-twitter"></i></a></li>
                                                <li><a href=""><i class="icon-linkedin"></i></a></li>
                                        </ul>
                                        <ul><li> &nbsp; </li></ul>
                                </div>
                        </div>
                </div>
                <div class="span3">
                        <div class="team-member">
                                <div class="member-photo"> <a class="thumbnail" href="#gopal" data-toggle="modal"> <img alt="" src="/img/core/mr_gopal.jpg" class=""> </a> </div>
                        </div>
                </div>
        </div>
</div>
</div>
