<link href='http://fonts.googleapis.com/css?family=Port+Lligat+Slab' rel='stylesheet' type='text/css'>
<style>
.about-intro {
    color: #333;
    font-size: 14px;
    margin: 0 0 80px;
}
.about-intro h4 {
    margin: 0 0 20px;
}
.team-member {
    background: #fff;
    border: 2px solid #C9C;
    border-bottom: 3px solid #ffd800;
    margin-bottom: 30px;
    -webkit-transition: border .2s ease-out;
    -moz-transition: border .2s ease-out;
    -ie-transition: border .2s ease-out;
    -o-transition: border .2s ease-out;
    transition: border .2s ease-out;
}
.team-member:hover {
    border-bottom: 3px solid #d73300;
}
.member-photo img {
    display: block;
    width: 100%;
}
.member-info {
    display: block;
    padding: 16px 15px 9px;
}
.member-info h4 {
    color: #d73300;
    margin: 0;
}
.member-info .position {
    color: #959595;
    display: block;
    margin-bottom: 15px;
}
.member-info p {
    border-bottom: 1px dotted #d9d9d9;
    border-top: 1px dotted #d9d9d9;
    margin: 10px 0;
    padding: 20px 0;
}
.member-social-links {
    display: inline-block;
    margin: 0;
}
.member-social-links li {
    display: block;
    float: left;
}
.member-social-links a {
    color: #959595;
    font-size: 12px;
    letter-spacing: 1px;
    margin-right: 10px;
    text-transform: uppercase;
}
.member-social-links a:hover {
    color: #d73300;
}
.dropcap {
    font-family: Georgia, serif;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
    
    font-size: 18px;
	color:#000;
    text-shadow: 1px 1px 0 #fafafa, 1px 1px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.comment-title {
    color: #333;
    font-size: 19px;
    text-transform: uppercase;
    line-height: 0;
    margin-bottom: 25px;
	margin-top:50px;
}  
body {
    #font-family:'Arial';
    background:  url(/img/b.png) repeat;
}
.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 10px;
    text-align: center;
    text-transform: capitalize;
}
.newfont{
	font-family: 'Port Lligat Slab', serif;
	border-bottom:#C33 dotted 2px;
}
.newfont2{
 font: 13px/1.7em 'Open Sans';
font-family: 'Open Sans';
font-size: 18px;
font-style: normal;
font-variant: normal;
font-weight: normal;
line-height: 1.3em;
text-align:justify;

}

</style>


<!--
<div class="container-footer" style="background:url('/img/wave.png') repeat; height:50px;">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
                CANOPY ONE OVERVIEW
                    </div>
        </div>
    </div>
</div>
-->
<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12">
     <img src="/img/image4.jpg" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>


<div class="container">
                   <div class="row">
		<div class="span10 hero-unit offset1">
			<h1>Meet Our Team</h1>
		</div></div>
        <div class="row">

           <div class="span1"> &nbsp;    
            </div>
   <div class="span2">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/author_1.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Dip Biswas</h4>
                            <span class="position">Founder/Partner</span>
                            <p>Sed nunc tortor, sagittis quis viverra id, molestie vitae nibh. Donec vitae lacus sed risus consectetur.
                          <a href="#myModal1"   data-toggle="modal" style="color:#933"> Read more </a>
                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/author_1.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Dip Biswas</h4>
                            <span class="position">Founder/Partner</span>
                            <p>Sed nunc tortor, sagittis quis viverra id, molestie vitae nibh. Donec vitae lacus sed risus consectetur.
                                                      <a href="#myModal1"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                                <li><a href=""><i class=" icon-facebook"></i></a></li>
                                <li><a href=""><i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/author_1.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Dip Biswas</h4>
                            <span class="position">Founder/Partner</span>
                            <p>Sed nunc tortor, sagittis quis viverra id, molestie vitae nibh. Donec vitae lacus sed risus consectetur.
                                                      <a href="#myModal1"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>


                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/author_1.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Dip Biswas</h4>
                            <span class="position">Founder/Partner</span>
                            <p>Sed nunc tortor, sagittis quis viverra id, molestie vitae nibh. Donec vitae lacus sed risus consectetur.
                                                      <a href="#myModal1"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>


                            </ul>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="team-member">
                        <div class="member-photo">
                            <img alt="" src="/img/author_1.jpg">
                        </div>
                        <div class="member-info">
                            <h4>Dip Biswas</h4>
                            <span class="position">Founder/Partner</span>
                            <p>Sed nunc tortor, sagittis quis viverra id, molestie vitae nibh. Donec vitae lacus sed risus consectetur.
                                                      <a href="#myModal1"   data-toggle="modal" style="color:#933"> Read more </a>

                            </p>
                            <ul class="member-social-links">
                               <li><a href=""> <i class=" icon-facebook"></i></a></li>
                               <li><a href=""> <i class="  icon-twitter"></i></a></li>
                                <li><a href=""><i class="icon-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
           <div class="span1"> &nbsp;    
            </div>

   </div>
    </div>
    </div>
    <div class="row">
    <div class="span1">&nbsp;</div>
    <div class="span10" style="margin-left:80px;">
 <SPAN style="font-size: 30px;" 
class="newfont">Corporate Social Responsibility </br> &nbsp;</SPAN>
<img src="/img/cop.jpg" style="margin-top:20px;margin-bottom:30px;"/>
<span class="newfont2"><P>Corporate Social Responsibility agenda at Canopy One are guided by one common commitment: To reach out to the community, to lead healthy and happy lives. Our initiatives focus on what is right to our employees, clients, community and the environment. We believe that we can build a stable community and a world together.</P><p>

Canopy one is focus to build an organizational culture by encouraging its employees to involve actively in community development programs and also to take part in any voluntary organization programs on Health, Education or Environmental awareness programs. Canopy one also promotes actively Save Water / Save Energy or Save Paper consciously and especially practices by adopting all the documentations in the office as e-documentation mostly. Equipping US Citizens and Veterans with Workforce Skills</p><p>

Canopy One is in the process of collaborating with Non Profit Organizations and Virginia International University (VIU) to develop workforce training programs for the US citizens. These programs will impart Information Technology skills through education and onsite training that targets the unemployed, under-employed US citizens, returning veterans and under-privileged youth.</p><p>

Canopy one encourages non- technical students or veterans to contact our office for any assistance in IT information or skills training & development 
</p></span>
</div>
<div class="span1"></div>


  </div>  
    
    
    
    
    
    
    
    
    
    <!-- Modal -->
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> Mr... </h3>
  </div>
  <div class="modal-body">
    <p>
    <div class="row">
			<div class="login-content span4 mod">
				
			</div>
		<div>
	</div>
</div>
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary"></button>
  </div>
</div>

