<style>
body {
    
    background: #FFF;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/diff.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap">O</span><span >What makes us unique in the IT industry is the focus on bringing cost-effective solutions to the critical projects which enhances the ROI for our customers</span> </p>
</div></div></div>


<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
<h3><i class="icon-forward" style="color:#f08c58;font-size:18px;margin-right:10px;margin-left:30px;"></i> 
Our approach is Customer centric ….</h3></br></br>
<p>
<span class="dropcap" style="color:#960;margin-right:15px;"><i class="icon-umbrella"></i></span>We make sure we understand our client's needs and objectives, understand the business goals more thoroughly, followed by building the solutions around our client's business models.</span></br></br></br>
</p>
<p>
<span class="dropcap" style="color:#48c0d2;margin-right:20px;"><i class=" icon-globe"></i></span>Second important aspect we believe in is the speed in which we provide solutions to our clients. This is possible because our team is comprised of extraordinary talented senior professionals whom have many years of experience and expertise coming from different industry verticals. 
</br></br></br>
</p>
<p>
<span class="dropcap" style="color:#3C6;margin-right:20px;"><i class=" icon-th-large"></i></span>This enables us to handle any issue on latest technology verticals. Our team understands your concerns more efficiently with clarity. Because of the investments you make we recognize and what you expect is more value for money from the investment. We guarantee that we will help you find and deliver that value through our uncompromising focus on your business objectives. </br></br></br>
</p>
<p>
  <span class="dropcap" style="color:#609;margin-right:20px;"><i class="icon-group"></i></span>Our delivery mechanisms guarantee our clients satisfaction and this is evident as Canopy One is at present in a niche position. We are focused to ensure and maintain the position we have achieved over these years in providing IT solutions for various technology areas.
</p>
   
   </div></div></div>

</br></br></br></br></br></br>

