<style>
.containtfont {
    
    font-size: 18px;
	color:#000;
    text-shadow: 1px 1px 0 #fafafa, 1px 1px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

body {
    
    background:  url(/img/b.png) repeat;
}

.big-intro {
	font-size: 28px;
	line-height: 1.7em;
	color: #888;
	
	padding: 25px 0;
	
	border: 1px dotted #CCC;	
	border-right: none;
	border-left: none;
}
.slash {
padding-right: .25em;
color: #81994D;
}
.nis1 {
line-height: 27px !important;
font-size: 188x;
font-weight: bold;
}
</style>


<div class="container-footer" style="background:#FFF ;">
<div class="container" >
<div class="row" >
   <div class="span12">
     <img src="/img/image1.jpg">
   </div>
</div>
</div>
</div>

<div class="container-footer" style="background:url('/img/wave.png') repeat; height:50px;">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
                CANOPY ONE OVERVIEW
                    </div>
        </div>
    </div>
</div>

<div id="subpage">	
	
	<div class="container">
		
		
		<div class="row">
			
			<div class="span12">
				
				<div class="big-intro">We are regarded as industry leaders in IT strategy and solutions, focused solely on delivering great user experiences.</div>
				
			</div> <!-- /span12 -->
			
		</div> <!-- /row -->
		
		<br /><br />
		
		
		
		<div class="row">
			
			<div class="span12">				
				<h3 ><span class="slash">//</span > <span class="nis1">About The Product</span></h3>
			</div> <!-- /span12 -->	
					
			
			<div class="span6">		
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					
					
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					
			</div> <!-- /span6 -->	
			
			<div class="span6">		
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					
					
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
					
			</div> <!-- /span6 -->			
			
		</div> <!-- /row -->
</div></div>    







    
    <!-- Modal -->
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> My CanopyOne Login </h3>
  </div>
  <div class="modal-body">
    <p>
    <div class="row">
			<div class="login-content span4 mod">
				
			</div>
		<div>
	</div>
</div>
    
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary">Sign Up</button>
  </div>
</div>

