<style>
body {
    
    background: #FFF;
	font-size:15px;
}
code, pre {
  border-bottom-left-radius:3px;
  border-bottom-right-radius:3px;
  border-top-left-radius:3px;
  border-top-right-radius:3px;
  color:#333333;
  font-family:Menlo, Monaco, Consolas, 'Courier New', monospace;
  font-size:12px;
  padding:0 3px 2px;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

.bb
{
	color:#5683be;
	margin-right:10px;
	font-size:22px;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/news.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->



<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
<ul style="margin-left:22px;">
<li class="icon-circle-arrow-right">
Canopy One started its new incorporation of <font class="cc">Canopy One Solutions India Pvt. Ltd.</font> March 2012.
</li>
<li class="icon-circle-arrow-right">
Canopy One started its Canada Operations through <font class="cc">Canopy One Solutions Canada Inc.</font> 
</li>
<li class="icon-circle-arrow-right">
Sponsored   sports event at   Liberty Elementary School, Chantilly VA, - Mat ball game where teachers, parents and children have participated in the month March 2012.
</li>
<li class="icon-circle-arrow-right">

Participation in community programmes on Promoting Health & fitness for better health and living.
</li>
<li class="icon-circle-arrow-right">
Get together of Canopy One Employees families on the 'New year Day' celebrations 2012.
</li>
<li class="icon-circle-arrow-right">
Celebration of Independence Day   both in India and US. 
</li>
<li class="icon-circle-arrow-right">
Canopy One sponsored cricket sport kits to youth of Chantilly to both WMCL and LCCL (Loudon   County Cricket League).
</li>
<li class="icon-circle-arrow-right">
Canopy One believes in returning its share to the community by providing sponsorship of education to needy students at the college degree level in India 
</li>
</ul>
   
   </div></div></div>

</br></br></br></br></br></br>

