<style>
body {
    
    background: #FFF;
}
code, pre {
  border-bottom-left-radius:3px;
  border-bottom-right-radius:3px;
  border-top-left-radius:3px;
  border-top-right-radius:3px;
  color:#333333;
  font-family:Menlo, Monaco, Consolas, 'Courier New', monospace;
  font-size:12px;
  padding:0 3px 2px;
}
pre {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif !important;

  background-color:#ffffff !important;
  border:1px solid rgba(0, 0, 0, 0.14902);
  border-bottom-left-radius:4px;
  border-bottom-right-radius:4px;
  border-top-left-radius:4px;
  border-top-right-radius:4px;
  display:block;
  font-size:15px !important;
  line-height:18px;
  margin:0 0 9px;
  padding:8.5px;
  white-space:pre-wrap;
  word-break:break-all;
  word-wrap:break-word;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

.bb
{
	color:#5683be;
	margin-right:10px;
	font-size:22px;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/news.png" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->



<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
<pre>
<i class="icon-bullhorn bb"></i>Canopy One started its new incorporation of <font class="cc">Canopy One Solutions India Pvt. Ltd.</font> March 2012.
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Canopy One started its Canada Operations through <font class="cc">Canopy One Solutions Canada Inc.</font> 
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Sponsored   sports event at   Liberty Elementary School, Chantilly VA, - Mat ball game where teachers, parents and children have participated in the month March 2012.
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Participation in community programmes on Promoting Health & fitness for better health and living.
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Get together of Canopy One Employees families on the 'New year Day' celebrations 2012.
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Celebration of Independence Day   both in India and US. 
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Canopy One sponsored cricket sport kits to youth of Chantilly to both WMCL and LCCL (Loudon   County Cricket League).
</pre>
<pre>
<i class="icon-bullhorn bb"></i>Canopy One believes in returning its share to the community by providing sponsorship of education to needy students at the college degree level in India 
</pre>
   
   </div></div></div>

</br></br></br></br></br></br>

