<style>
body {
	background: #FFF !important;
	font-size: 15px !important;
}
.big-intro {
	font-size: 24px;
	line-height: 1.7em;
	color: #888;
	padding: 25px 0;
	font-family: 'Alegreya SC', serif;
	border: 1px dotted #CF6;
	border-right: none;
	border-left: none;
}
.slash {
	padding-right: .25em;
	color: #C00;
}
.nis1 {
	line-height: 27px !important;
	font-size: 188x;
	font-weight: bold;
}
#subpage {
	margin-top: 3em;
	margin-bottom: 2.5em;
}
.about-intro {
	color: #333;
	font-size: 14px;
	margin: 0 0 80px;
}
.about-intro h4 {
	margin: 0 0 20px;
}
.team-member {
	background: #fff;
	border: 2px solid #C9C;
	border-bottom: 3px solid #ffd800;
	margin-bottom: 30px;
 -webkit-transition: border .2s ease-out;
 -moz-transition: border .2s ease-out;
 -ie-transition: border .2s ease-out;
 -o-transition: border .2s ease-out;
 transition: border .2s ease-out;
}
.ml {
	margin-left:10px;
}
.member-photo img {
	display: block;
	width: 100%;
}
.member-info {
	display: block;
	padding: 16px 15px 9px;
}
.member-info h4 {
	color: #d73300;
	margin: 0;
}
.member-info .position {
	color: #959595;
	display: block;
	margin-bottom: 15px;
}
.member-info p {
	border-bottom: 1px dotted #d9d9d9;
	border-top: 1px dotted #d9d9d9;
	margin: 10px 0;
	padding: 20px 0;
}
.member-social-links {
	display: inline-block;
	margin: 0;
}
.member-social-links li {
	display: block;
	float: left;
}
.member-social-links a {
	color: #959595;
	font-size: 12px;
	letter-spacing: 1px;
	margin-right: 10px;
	text-transform: uppercase;
}
.member-social-links a:hover {
	color: #d73300;
}
.dropcap {
	font-family: Georgia, serif;
	font-size: 55px;
	color:#f06921;
	padding: 0 7px 5px 0;
	line-height: 1em;
	float: left;
	text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
	font-size: 24px;
	color:#000;
	text-decoration : underline;
}
.comment-title {
	color: #333;
	font-size: 19px;
	text-transform: uppercase;
	line-height: 0;
	margin-bottom: 25px;
	margin-top:50px;
}
hero-unit h1 {
	background: url("../img/h.png") no-repeat scroll center top transparent;
	color: #7B0202;
	font-family: 'Lobster', cursive;
	font-size: 22px;
	font-weight: normal;
	margin: 25px 0;
	padding-right: 10px;
	text-align: center;
	text-transform: capitalize;
}
.test {
	border-bottom: 2px solid #ccc !important;
}
.test {
	background: none repeat scroll 0 0 #FFFFFF;
	border: 1px solid #EEEEEE;
	margin: 5px 0 0;
	padding: 8px 12px;
}
.test:hover {
	border-bottom: 2px solid #f06921 !important;
	-webkit-transition:border-bottom 1s ease;
	-moz-transition:border-bottom 1s ease;
	-o-transition:border-bottom 1s ease;
	transition:border-bottom 1s ease;
}
.test > a {
	color: #777777;
	font-style: italic;
}
.test> a:hover {
	color:#f06921 !important;
	-webkit-transition:color 1s ease !important;
	-moz-transition:color 1s ease !important;
	-o-transition:color 1s ease !important;
	transition:color 1s ease !important;
}
.tauth {
	color: #888888;
	font-weight: 300;
	left: 10px;
	position: relative;
	top: -6px;
}
.tauth > a:hover {
	color: #f06921 !important;
	font-size: 14px !important;
	text-decoration: none !important;
}

.link a{color:#f06921; text-decoration:underline;}

 <link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>

<div class="coretop">
        <div class="container" >
                <div class="row" >
                        <div class="span12" > <img src="/img/image1.jpg" style="margin-top:8px;" > </div>
                </div>
        </div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
<div class="span12" style="text-align:justify;margin-top:20px;">
        <p> Canopy One Solutions Inc. is a fast growing software development, end-to-end information technology services and solutions provider based out of Chantilly Virginia USA. Canopy One was established with the objective of providing innovative solutions that help clients align their IT strategy with business goals within their budgetary parameters by combining cost effective consulting solutions and collaborative engagement models.</p>
        <p> For more than 15 years Canopy One management team has successfully developed, delivered and managed technology solutions for our clients. Since our inception, we have been harnessing the power of Information Technology to help our clients secure a competitive edge in their industries.</p>
        <p> Our clients not only praise our comprehensive range of services, our innovative, streamlined and cost effective solutions, but more importantly they praise our high level of excellent customer service which is unparalleled in the industry. </p>
        <p> Canopy one's Onsite, Offsite, Near shore and offshore service expertise  across several technology verticals and different industry sectors have positioned our self in niche area of IT services and consulting.  The services rendered by our talented IT professionals in this area have received high customer satisfaction to handle critical projects across different industry sectors. </p>
        <p class="link"> We have strategically positioned ourselves with a global foot print of offices in the USA, Canada, Europe, Latin America  and India, to serve your needs anywhere you need in the world. Canopy One has a state of art Global Delivery center at Hyderabad in India, handling mission critical projects for their clients in key technology areas like <a href="">Integration Services</a>, <a href="">Application Services</a>, <a href="">DW & BI Services</a> ,<a href=""> Consulting and Professional Services</a></p>
        </br>
</div>
</div></div>

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;">
   <p>What makes us unique in the IT industry is the focus on bringing cost-effective solutions to the critical projects which enhances the ROI for our customers</span> </p>
</div></div></div>


<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;">
<h2 class="head">Our approach is Customer centric ….</h2>
</br>
<ul style="margin-left:22px;">
 <li class="icon-circle-arrow-right">We make sure we understand our client's needs and objectives, understand the business goals more thoroughly, followed by building the solutions around our client's business models.</li>

 <li class="icon-circle-arrow-right">Second important aspect we believe in is the speed in which we provide solutions to our clients. This is possible because our team is comprised of extraordinary talented senior professionals whom have many years of experience and expertise coming from different industry verticals. </li>

 <li class="icon-circle-arrow-right">This enables us to handle any issue on latest technology verticals. Our team understands your concerns more efficiently with clarity. Because of the investments you make we recognize and what you expect is more value for money from the investment. We guarantee that we will help you find and deliver that value through our uncompromising focus on your business objectives. </li>

  <li class="icon-circle-arrow-right"> Our delivery mechanisms guarantee our clients satisfaction and this is evident as Canopy One is at present in a niche position. We are focused to ensure and maintain the position we have achieved over these years in providing IT solutions for various technology areas.</li></ul>
 </div></div></div>
   </br></br></br></br></br></br>

