<style>
.big-intro {
	font-size: 24px;
	line-height: 1.7em;
	color: #888;
	padding: 25px 0;
	font-family: 'Alegreya SC', serif;
	border: 1px dotted #CF6;	
	border-right: none;
	border-left: none;
}
.slash {
padding-right: .25em;
color: #C00;
}
.nis1 {
line-height: 27px !important;
font-size: 188x;
font-weight: bold;
}
#subpage {
	margin-top: 3em;
	
	margin-bottom: 2.5em;
}

.about-intro {
    color: #333;
    font-size: 14px;
    margin: 0 0 80px;
}
.about-intro h4 {
    margin: 0 0 20px;
}
.team-member {
    background: #fff;
    border: 2px solid #C9C;
    border-bottom: 3px solid #ffd800;
    margin-bottom: 30px;
    -webkit-transition: border .2s ease-out;
    -moz-transition: border .2s ease-out;
    -ie-transition: border .2s ease-out;
    -o-transition: border .2s ease-out;
    transition: border .2s ease-out;
}
.team-member:hover {
    border-bottom: 3px solid #d73300;
}
.member-photo img {
    display: block;
    width: 100%;
}
.member-info {
    display: block;
    padding: 16px 15px 9px;
}
.member-info h4 {
    color: #d73300;
    margin: 0;
}
.member-info .position {
    color: #959595;
    display: block;
    margin-bottom: 15px;
}
.member-info p {
    border-bottom: 1px dotted #d9d9d9;
    border-top: 1px dotted #d9d9d9;
    margin: 10px 0;
    padding: 20px 0;
}
.member-social-links {
    display: inline-block;
    margin: 0;
}
.member-social-links li {
    display: block;
    float: left;
}
.member-social-links a {
    color: #959595;
    font-size: 12px;
    letter-spacing: 1px;
    margin-right: 10px;
    text-transform: uppercase;
}
.member-social-links a:hover {
    color: #d73300;
}
.dropcap {
	
    font-family: Georgia, serif;
    font-size: 55px;
	color:#f06921;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
    
    font-size: 24px;
	color:#000;
	text-decoration : underline;
}
.comment-title {
    color: #333;
    font-size: 19px;
    text-transform: uppercase;
    line-height: 0;
    margin-bottom: 25px;
	margin-top:50px;
}  
body {
    
    background: #FFF;
}
.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 10px;
    text-align: center;
    text-transform: capitalize;
}

<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12" >
     <img src="/img/image1.jpg" style="margin-top:8px;" >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap">C</span><span >anopy One Solutions Inc. is a fast growing software and development company providing innovative solutions based out of Chantilly Virginia USA. Canopy One has a state of art software development center at Hyderabad in India. Canopy One has handling projects with its talented IT professionals experienced in different technologies to providing   quality solutions. Our services are based on industry best practices to deliver solution using proven technology resources.</span> </p>
   <p>Canopy One Solutions was established with the objective of providing professional solutions and resources filling the gap between end client's needs and implementers globally. We have strategically positioned ourselves to provide solutions with the best qualified resources within your budgetary parameters to help you complete time sensitive critical projects and we do this by providing you a focused range of cost effective solutions.</p></br>
   
   <div class="row"><div class="span12">
 <span class="c" >Canopy One has rich experience in some of the key technology areas like</span></div></br></br>
 <div class="span1">&nbsp;</div>
  <div class="span4">
<img src="/img/aboutus/1.png" width="90px"/>Data warehousing and ETL</br>
<img src="/img/aboutus/2.png" width="90px"/>Business Intelligence solutions</br>
 </div>
<div class="span4">
<img src="/img/aboutus/3.png" width="90px"/>System integration services</br>
<img src="/img/aboutus/4.png" width="90px"/>Business consulting services </div>
<div class="span3">
<img src="/img/aboutus/5.png" width="90px"/>Cloud technologies</br>
<img src="/img/aboutus/1.png" width="90px"/>Ruby on Rails </div>
</div>
</br></br>
<p><img src="/img/aboutus/hill.png" align="right" style="margin-right:20px;width:250px;"/><span class="dropcap">F</span>or more than 15 years, Canopy One has successfully developed, delivered and managed technology solutions for our clients. Since our inception, we have been harnessing the power of Information Technology to help our clients secure a competitive edge in their industries. Our clients not only praise our comprehensive range of services, our innovative, streamlined and cost effective solutions, but more importantly they praise our high level of excellent customer service which is unparalleled in the industry.

Canopy one has established a separate division to handle IT outsourcing services to multiple industry verticals for more than a decade. The services rendered by our talented IT professionals in this area have received high customer satisfaction to handle critical projects across different industry sectors.

With offices in the USA, Canada, Europe and India Canopy One has established a global foot print and therefore able to serve your needs anywhere you need.
</p>
   </div>
</div>
</div>

<div id="subpage">	
	
	<div class="container">
		
		
		<div class="row">
			
			<div class="span12">				
				<h3 > <span  style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;">OUR MISSION</span></h3>
			</div> <!-- /span12 -->	
					
			
			<div class="span12" style="text-align:justify;margin-top:20px;">		
					<p><img src="/img/aboutus/light.png" align="left" style="margin-right:20px;height:180px;width:200px"/><i class="icon-forward c"></i>To deliver cost effective IT resources and solutions that will enable clients to attain a cutting edge cost effective solutions addressing multi industry needs and be &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;successful in a highly competitive global environment through its state of art technology center.</br>
<i class="icon-forward c"></i>To partner as knowledge sharing key associate to   help and unleash the information that will bring a positive change   to client's business. </br>
<i class="icon-forward c"></i>To provide scalable and modular applications that will support business expansion and   know how to integrate solutions with both internal and external systems to &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;create seamless workflows. </br>
<i class="icon-forward c"></i>To provide cost effective, simple solution for an application right from its conception, design, development, deployment and management. </br>
<i class="icon-forward c"></i>To provide a 24X7 training & development on different technological verticals for Manpower resources and knowledge sharing partners.</br>
</p>
					
					
			</div> <!-- /span12 -->
	

            			
			
			
		</div> <!-- /row -->
</div></div>    





