<style>

.big-intro {
	font-size: 24px;
	line-height: 1.7em;
	color: #888;
	
	padding: 25px 0;
	font-family: 'Alegreya SC', serif;
	border: 1px dotted #CF6;	
	border-right: none;
	border-left: none;
}
.slash {
padding-right: .25em;
color: #C00;
}
.nis1 {
line-height: 27px !important;
font-size: 188x;
font-weight: bold;
}
#subpage {
	margin-top: 3em;
	
	margin-bottom: 2.5em;
}





.about-intro {
    color: #333;
    font-size: 14px;
    margin: 0 0 80px;
}
.about-intro h4 {
    margin: 0 0 20px;
}
.team-member {
    background: #fff;
    border: 2px solid #C9C;
    border-bottom: 3px solid #ffd800;
    margin-bottom: 30px;
    -webkit-transition: border .2s ease-out;
    -moz-transition: border .2s ease-out;
    -ie-transition: border .2s ease-out;
    -o-transition: border .2s ease-out;
    transition: border .2s ease-out;
}
.team-member:hover {
    border-bottom: 3px solid #d73300;
}
.member-photo img {
    display: block;
    width: 100%;
}
.member-info {
    display: block;
    padding: 16px 15px 9px;
}
.member-info h4 {
    color: #d73300;
    margin: 0;
}
.member-info .position {
    color: #959595;
    display: block;
    margin-bottom: 15px;
}
.member-info p {
    border-bottom: 1px dotted #d9d9d9;
    border-top: 1px dotted #d9d9d9;
    margin: 10px 0;
    padding: 20px 0;
}
.member-social-links {
    display: inline-block;
    margin: 0;
}
.member-social-links li {
    display: block;
    float: left;
}
.member-social-links a {
    color: #959595;
    font-size: 12px;
    letter-spacing: 1px;
    margin-right: 10px;
    text-transform: uppercase;
}
.member-social-links a:hover {
    color: #d73300;
}
.dropcap {
    font-family: Georgia, serif;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
    
    font-size: 24px;
	color:#000;
	text-decoration : underline;
   
   
    
}

.comment-title {
    color: #333;
    font-size: 19px;
    text-transform: uppercase;
    line-height: 0;
    margin-bottom: 25px;
	margin-top:50px;
}  
body {
    
    background: #FFF;
}
.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 10px;
    text-align: center;
    text-transform: capitalize;
}
<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>


<div class="container-footer" style="background:#FFF ;">
<div class="container" >
<div class="row" >
   <div class="span12">
     <img src="/img/image1.jpg"  >
   </div>
</div>
</div>
</div>
<!--
<div class="container-footer" style="background:#404040">
<div class="container">
            <div class="row">
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;" >
               <!-- <img src="/img/about1.png" /> ABOUT US
                    </div>
        </div> 
    </div>
</div> -->

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> <span class="dropcap">C</span><span >anopy One Solutions is in the business of 
    providing technology solutions partnering with IT companies ranging from Mid-scale to large scale firms. 
    Canopy one has experienced professionals with abundant skills and talent gained over the years working in 
    different industry sector. The company has been established with an objective of providing professional 
    resources filling the gap between end client's needs and tasks undertakers. The manpower resources, technology
     upgrades and insights into market demands are well compensated through constant innovation in its approach.
      In this endeavor Canopy one has established a full-fledged training and development center in India based out 
      of Hyderabad. The training center is equipped with talented experienced trainers who are available 24X7 for 
      providing both on site and off shore technical support for both the consultants and technology partners over 
      the years.
Strategically Canopy one is positioned to provide manpower resources by selecting right candidates for the
 right position. It has been partnering with fortune 500 companies in understanding key technological verticals and 
 client's requirements on the talents to accomplish the specific IT projects.</span></p>
   </div>
</div>
</div>

<div id="subpage">	
	
	<div class="container">
		
		
		<div class="row">
			
			<div class="span12">				
				<h3 > <span  style="text-align:justify;font-size:24px;color:#f06921;margin-top:15px;">OUR MISSION</span></h3>
			</div> <!-- /span12 -->	
					
			
			<div class="span12" style="text-align:justify;margin-top:20px;">		
					<p><img src="/img/1.png" align="left" style="margin-right:20px;height:100px;"/><span class="dropcap">T</span>O deliver the best, cost effective IT resources and solutions that will enable clients to attain a cutting edge cost effective solutions addressing multi industry needs and be successful in a highly competitive global environment through its state of art technology center.
To partner as knowledge sharing key associate to help and unleash the information that will bring a positive change to client's business. 
To provide software development and consulting services to build Application Integration on Data Warehousing & Business Intelligence.
To provide scalable and modular applications that will support business expansion and know how to integrate solutions with both internal and external systems to create seamless workflows. 
To provide cost effective, simple solution for an application right from its conception, design, development, deployment and management. 
To provide a 24X7 training & development on different technological vertical for Manpower resources and knowledge sharing partners</p>
					
					
			</div> <!-- /span6 -->
            			
			
			
		</div> <!-- /row -->
</div></div>    






