<style>
body {
    
    background: #FFF !important;
	font-size: 15px !important;
}


#subpage {
	margin-top: 3em;
	
	margin-bottom: 2.5em;
}
.about-intro {
    color: #333;
    font-size: 14px;
    margin: 0 0 80px;
}
.about-intro h4 {
    margin: 0 0 20px;
}
.team-member {
    background: #fff;
    border: 2px solid #C9C;
    border-bottom: 3px solid #ffd800;
    margin-bottom: 30px;
    -webkit-transition: border .2s ease-out;
    -moz-transition: border .2s ease-out;
    -ie-transition: border .2s ease-out;
    -o-transition: border .2s ease-out;
    transition: border .2s ease-out;
}
.team-member:hover {
    border-bottom: 3px solid #d73300;
}
.member-photo img {
    display: block;
    width: 100%;
}
.member-info {
    display: block;
    padding: 16px 15px 9px;
}
.member-info h4 {
    color: #d73300;
    margin: 0;
}
.member-info .position {
    color: #959595;
    display: block;
    margin-bottom: 15px;
}
.member-info p {
    border-bottom: 1px dotted #d9d9d9;
    border-top: 1px dotted #d9d9d9;
    margin: 10px 0;
    padding: 20px 0;
}
.member-social-links {
    display: inline-block;
    margin: 0;
}
.member-social-links li {
    display: block;
    float: left;
}
.member-social-links a {
    color: #959595;
    font-size: 12px;
    letter-spacing: 1px;
    margin-right: 10px;
    text-transform: uppercase;
}
.member-social-links a:hover {
    color: #d73300;
}
.dropcap {
    font-family: Georgia, serif;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.dropcapsmall {
	font-family: Georgia, serif;
	font-size: 20px;
	color:#f06921;
	opacity:0.9;
	padding: 0 7px 5px 0;
	margin-top:1px;
	line-height: 1em;
	float: left;
	text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}
.containtfont {
    
    font-size: 24px;
	color:#000;
	text-decoration : underline;
}
.comment-title {
    color: #333;
    font-size: 19px;
    text-transform: uppercase;
    line-height: 0;
    margin-bottom: 25px;
	margin-top:50px;
}  
.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 10px;
    text-align: center;
    text-transform: capitalize;
}
.social { color:#039;
    font-size: 20px;
    font-weight: normal;
	font-family: 'Port Lligat Slab', serif;
}
.ico{color:#000;margin-right:10px;}
#terminal {
		background-color:#FFF !important;
		color:#039 !important;
		font-size: 20px !important;
}

<link href='http://fonts.googleapis.com/css?family=Port+Lligat+Slab' rel='stylesheet' type='text/css'>
</style>


<div class="coretop">
<div class="container" >
<div class="row" >
   <div class="span12">
     <img src="/img/corporate.png"  style="margin-top:8px">
   </div>
</div>
</div>
</div>

<div class="coretop" style="background:url('/img/') repeat; height:50px;">
<div class="container">
            <div class="row">
                <div class="span12">
                <h2 class="head">Corporate Social Responsiablity</h2>
                 </div>
        </div>
    </div>
</div>

<div class="container">
<div class="row">
<div class="span12" style="text-align:justify;margin-top:20px;" >
    <ul style="margin-left:22px;">
    <li class="icon-circle-arrow-right">To reach out to the community, to lead healthy and happy lives. Our initiatives focus on what is right to our employees, clients, community and the environment. We believe that we can build a stable community and a world together.</br></li>
    <li></li>
    <li class="icon-circle-arrow-right">Canopy one is focus to build an organizational culture by encouraging its employees to involve actively in community development programs and also to take part in any voluntary organization programs on Health, Education or Environmental awareness programs. Canopy one also promotes actively Save Water / Save Energy or Save Paper consciously and especially practices by adopting all the documentations in the office as e-documentation mostly. Equipping US Citizens and Veterans with Workforce Skills </br></li>
    <li></li>
    <li class="icon-circle-arrow-right">Canopy One is in the process of collaborating with Non Profit Organizations and Virginia International University (VIU) to develop workforce training programs for the US citizens. These programs will impart Information Technology skills through education and onsite training that targets the unemployed, under-employed US citizens, returning veterans and  under-privileged youth.</br></li>
    <li></li>
    <li class="icon-circle-arrow-right">Canopy one encourages non- technical students or veterans to contact our office for any assistance in IT information or skills training &amp; development programs.</br></li></ul>
</div>
</div>
</div>

<div id="subpage">	
	
	<div class="container">
		
		
		<br /><br />
		
		
		
</div></div>  

<script>


  </script>  

