<style>
body {
    
    background: #FFF;
}
.dropcap {
	
    font-family: Georgia, serif;
	margin-top:-10px;
    font-size: 55px;
    padding: 0 7px 5px 0;
    line-height: 1em;
    float: left;
    text-shadow: 1px 1px 0 #fafafa, 2px 2px 0 rgba(95, 149, 176, 0.5), 0 0 1px #fafafa;
}

.hero-unit h1 {
    background: url("../img/h.png") no-repeat scroll center top transparent;
    color: #7B0202;
    font-family: 'Lobster',cursive;
    font-size: 22px;
    font-weight: normal;
    margin: 25px 0;
    padding-right: 0px;
    text-align: center;
    text-transform: capitalize;
}

pre {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif !important;

  background-color:#ffffff !important;
  border:1px solid rgba(0, 0, 0, 0.14902);
  border-bottom-left-radius:4px;
  border-bottom-right-radius:4px;
  border-top-left-radius:4px;
  border-top-right-radius:4px;
  display:block;
  font-size:15px !important;
  line-height:18px;
  margin:0 0 9px;
  padding:8.5px;
  white-space:pre-wrap;
  word-break:break-all;
  word-wrap:break-word;
}

.tab-content {
  background-color:#000000;
  background-position:initial initial;
  background-repeat:initial initial;
  overflow:auto;
}

.nav-tabs {
    margin-bottom: 0;
    border-color: #dadada;
}
.nav-tabs li a {
    background-color: #ffffff !important;
    border: solid 1px #dadada;
    -moz-border-radius-topright: 3px;
    -webkit-border-top-right-radius: 3px;
    border-top-right-radius: 3px;
    -moz-border-radius-topleft: 3px;
    -webkit-border-top-left-radius: 3px;
    border-top-left-radius: 3px;
		color:#000000 !important;

}
.nav-tabs > li > a,
.nav-tabs > li > a:hover{
    border: solid 1px #dadada;
}
.nav-tabs > .active > a,
.nav-tabs > .active > a:hover {
    background-color: #f6f6f6 !important;
    border: solid 1px #DDD;
    border-bottom: solid 1px #f6f6f6;
	color:#f06921 !important;
}
.tab-content {
    padding: 10px;
    background: #f6f6f6;
    border: solid 1px #dadada;
    border-top: none;
    margin-bottom: 15px;
}



<link href='http://fonts.googleapis.com/css?family=Alegreya+SC:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</style>



<div class="container-footer" style="background:#fff !important;margin-top:9px;border-top:#FFF solid 1px;">
<div class="container">
            <div class="row">
                <img src="/img/contacts/usa.png" style="margin-top:0px;" id="usa">
                <img src="/img/contacts/canada.png" style="margin-top:0px;" id="canada">
                <img src="/img/contacts/hyd.png" style="margin-top:0px;" id="hyd">
 <!-- 
           
                <div class="span12" style="text-align:justify;font-size:24px;color:#f06921;" >
<iframe width="100%" height="322" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?t=m&amp;msa=0&amp;msid=205502136097723153377.0004cf925e9196ce8b41c&amp;source=embed&amp;ie=UTF8&amp;ll=35.173808,80.859375&amp;spn=86.785097,50.976562&amp;z=2&amp;output=embed"></iframe><br /><small> <a href="https://maps.google.com/maps/ms?t=m&amp;msa=0&amp;msid=205502136097723153377.0004cf925e9196ce8b41c&amp;source=embed&amp;ie=UTF8&amp;ll=35.173808,80.859375&amp;spn=86.785097,50.976562&amp;z=2" style="color:#0000FF;text-align:left;"> </a> </small>    -->
                    </div>
        </div> 
    </div>
</div> 

<div class="container">
<div class="row">
   <div class="span12" style="text-align:justify;margin-top:20px;">
   <p> 
   <div class="tabbable">
    <div class="row">
     <div class="span1">&nbsp;</div>
    <div class="span10">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#pane1" data-toggle="tab" id="usa1">USA Offices</a></li>
    <li><a href="#pane2" data-toggle="tab" id="hyd1">INDIA Offices</a></li>
    <li><a href="#pane3" data-toggle="tab" id="canada1" >CANADA Offices</a></li>
  </ul>
  </div>
       <div class="span1">&nbsp;</div>
</div>
    <div class="row">

     <div class="span1">&nbsp;</div>
     <div class="span10">
  <div class="tab-content">
    <div id="pane1" class="tab-pane active">
      <h2>World Headquarter:</h2>
      <table><tr><td valign="top" style="width:400px;">
      <pre><span style="font-size:18px;" class="cc">Canopy One Solutions</span></br><span style="font-size:15px;">4229 Lafayette Center Drive, Suite# 1625</br>Chantilly VA 20151</br></br>Phone : 703-831-8282 </br>Fax   : 703-345-0515</br>Email : CanopyUSA@CanopyOne.com</span>
      
      
      
      
    
    

    
    
      
      
      
</pre>
</td>
<td valign="top">
<pre>
<iframe width="525" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=4229+Lafayette+Center+Drive,+Suite%23+1625+Chantilly+VA+20151&amp;aq=&amp;sll=58.263287,-77.34375&amp;sspn=106.423671,316.054688&amp;ie=UTF8&amp;hq=&amp;hnear=4229+Lafayette+Center+Dr+%231625,+Chantilly,+Fairfax,+Virginia+20151&amp;t=m&amp;ll=38.910003,-77.472839&amp;spn=0.023376,0.045061&amp;z=14&amp;output=embed"></iframe><br /></pre>
</td></tr></table>
    </div>
    <div id="pane2" class="tab-pane">
      <h2>Global Delivery Center:</h2>
      <table><tr><td valign="top" style="width:400px;">
      <pre><span style="font-size:18px;" class="cc">Canopy One IT Solutions India Pvt. Ltd</span></br><span style="font-size:15px;">4Plot #7/1, Sector-3, HUDA Techno Enclave,</br>Opp. Mind space Rhea IT Park</br>Hyderabad, India - 500 081</br></br>Phone : +91 40 4020 2741</br>Email : CanopyIndia@CanopyOne.com</br>Website : www.CanopyOne.in
</span>
</pre>
 <pre><span style="font-size:18px;" class="cc">Canopy One IT Solutions India </span></br><span style="font-size:15px;">R S Towers, Plot No 171,</br>Hi Tech City, Kavuri Hills,</br>Phase II, Madhapur</br>Hyderabad India</br></br>Phone : 995-108-9994</br>Email : CanopyIndia@CanopyOne.com
</span>
</pre>

</td>
<td valign="top">
<pre>
<iframe width="525" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=4229+Lafayette+Center+Drive,+Suite%23+1625+Chantilly+VA+20151&amp;aq=&amp;sll=58.263287,-77.34375&amp;sspn=106.423671,316.054688&amp;ie=UTF8&amp;hq=&amp;hnear=4229+Lafayette+Center+Dr+%231625,+Chantilly,+Fairfax,+Virginia+20151&amp;t=m&amp;ll=38.910003,-77.472839&amp;spn=0.023376,0.045061&amp;z=14&amp;output=embed"></iframe><br /></pre>
</td></tr></table>
    </div>
    <div id="pane3" class="tab-pane">
            <h2>Canada Delivery Center::</h2>
      <table><tr><td valign="top" style="width:400px;">
      <pre><span style="font-size:18px;" class="cc">Canopy One Solutions</span></br><span style="font-size:15px;">87 E CAVENDISH ST, REGINA,</br>SK - S4N 5C1, Canada</br></br>Phone : 306-351-2125 </br>Email : CanopyIndia@CanopyOne.com</span>
      
      
      
      
    
    

    
    
      
      
      
</pre>
</td>
<td valign="top">
<pre>
<iframe width="525" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=87+E+CAVENDISH+ST,+REGINA,SK+-+S4N+5C1,+Canada&amp;aq=&amp;sll=50.453966,-104.55785&amp;sspn=0.007405,0.01929&amp;ie=UTF8&amp;hq=&amp;hnear=87+Cavendish+St,+Regina,+Saskatchewan+S4N+5N6,+Canada&amp;t=m&amp;z=11&amp;iwloc=A&amp;output=embed"></iframe><br /></pre></td></tr></table>

    </div>
    <div id="pane4" class="tab-pane">
  </div><!-- /.tab-content -->
  </div>
     <div class="span1">&nbsp;</div>
  
  
 </div>
</div><!-- /.tabbable -->
   
   
   
   
 </p>
</div></div></div></div>


</br></br></br></br></br></br>
<script>
								 $("#usa").show();
								 $("#canada").hide();
								 $("#hyd").hide();

	 $("#usa1").click(function(){
								 $("#usa").show();
								 $("#canada").hide();
								 $("#hyd").hide();
								 })
	 $("#canada1").click(function(){
								 $("#usa").hide();
								 $("#canada").show();
								 $("#hyd").hide();
								 })
	 $("#hyd1").click(function(){
								 $("#usa").hide();
								 $("#canada").hide();
								 $("#hyd").show();
								 })
</script>



